### ISSUE TITLE
Can't build on mingw

### ISSUE THREAD

**Issue by kireevco** [crosstool-ng/crosstool-ng#79] opened 2015-05-02 00:17 UTC
It also fails to build on mingw. I'm trying to elaborate build process here.
https://github.com/kireevco/packages/tree/master/esp-open-sdk/windows

Cross issue https://github.com/pfalcon/esp-open-sdk/issues/17

Full log:
```
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking for a BSD-compatible install... /usr/bin//install -c
checking for grep that handles long lines and -e... /usr/bin//grep
checking for egrep... /usr/bin//grep -E
checking for a sed that does not truncate output... /usr/bin//sed
checking whether sed understands -r -i -e... yes
checking whether ln -s works... no, using cp -p
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking for gobjcopy... no
checking for objcopy... objcopy
checking for absolute path to objcopy... /usr/bin/objcopy.exe
checking for gobjdump... no
checking for objdump... objdump
checking for absolute path to objdump... /usr/bin/objdump.exe
checking for greadelf... no
checking for readelf... readelf
checking for absolute path to readelf... /usr/bin/readelf.exe
checking for gperf... gperf
checking for absolute path to gperf... /usr/bin/gperf.exe
checking for bison... bison
checking for flex... flex
checking for makeinfo... makeinfo
checking for cut... cut
checking for stat... stat
checking for readlink... readlink
checking for wget... wget
checking for tar... tar
checking for gzip... gzip
checking for bzip2... bzip2
checking for patch... /usr/bin//patch
checking for bash >= 3.1... /usr/bin//bash
checking for GNU awk... /usr/bin//gawk
checking for GNU make >= 3.80... /usr/bin//make
checking whether /usr/bin//make sets $(MAKE)... yes
checking for make 3.81... yes
checking for GNU libtool >= 1.5.26... /usr/bin//libtool
checking for GNU libtoolize >= 1.5.26... /usr/bin//libtoolize
checking for GNU automake >= 1.10... /usr/bin//automake
checking for xz... xz
checking for cvs... cvs
checking for svn... no
checking for inline... inline
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for size_t... yes
checking for working alloca.h... no
checking for alloca... yes
checking libintl.h usability... no
checking libintl.h presence... no
checking for libintl.h... no
checking ncurses/ncurses.h usability... no
checking ncurses/ncurses.h presence... no
checking for ncurses/ncurses.h... no
checking ncurses/curses.h usability... no
checking ncurses/curses.h presence... no
checking for ncurses/curses.h... no
checking ncursesw/curses.h usability... no
checking ncursesw/curses.h presence... no
checking for ncursesw/curses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for library containing initscr... -lncurses
configure: creating ./config.status
config.status: creating Makefile
make MAKELEVEL=0
make: Entering directory `/c/Users/User/packages/esp-open-sdk/windows/mignw/esp-
open-sdk/crosstool-NG'
  SED    'ct-ng'
  SED    'scripts/crosstool-NG.sh'
  SED    'scripts/saveSample.sh'
  SED    'scripts/showTuple.sh'
  GEN    'config/configure.in'
  GEN    'paths.mk'
  GEN    'paths.sh'
  DEP    'nconf.gui.dep'
  DEP    'nconf.dep'
  DEP    'lxdialog/yesno.dep'
  DEP    'lxdialog/util.dep'
  DEP    'lxdialog/textbox.dep'
  DEP    'lxdialog/menubox.dep'
  DEP    'lxdialog/inputbox.dep'
  DEP    'lxdialog/checklist.dep'
  DEP    'mconf.dep'
  DEP    'conf.dep'
  BISON  'zconf.tab.c'
  GPERF  'zconf.hash.c'
(standard input):14: warning: junk after %% is ignored
, defaulting to Cage option ANSI-C
(standard input):5: junk after declaration
  LEX    'lex.zconf.c'
  DEP    'zconf.tab.dep'
  CC     'zconf.tab.o'
zconf.tab.c: In function `zconfparse':
zconf.tab.c:1656: error: `kconf_id_strings' undeclared (first use in this functi
on)
zconf.tab.c:1656: error: (Each undeclared identifier is reported only once
zconf.tab.c:1656: error: for each function it appears in.)
zconf.tab.c:1764: warning: initialization makes pointer from integer without a c
ast
zconf.tab.c: In function `zconf_endtoken':
zconf.tab.c:2315: error: `kconf_id_strings' undeclared (first use in this functi
on)
In file included from zconf.tab.c:2507:
lex.zconf.c: In function `zconflex':
lex.zconf.c:1103: warning: initialization makes pointer from integer without a c
ast
lex.zconf.c:1178: warning: initialization makes pointer from integer without a c
ast
make: *** [zconf.tab.o] Error 1
make: *** [build-lib-kconfig] Error 2
make: *** [build] Error 2
make: Leaving directory `/c/Users/User/packages/esp-open-sdk/windows/mignw/esp-o
pen-sdk/crosstool-NG'
make[1]: *** [_ct-ng] Error 2
make[1]: Leaving directory `/c/Users/User/packages/esp-open-sdk/windows/mignw/es
p-open-sdk/crosstool-NG'
make: *** [crosstool-NG/ct-ng] Error 2
```

**Comment by bhundven** [comment] 2015-05-07 18:50
My favorite question to currently ask (yes, we need to cut a release soon...), but are you running the 1.20.0 tarball or from latest git?

**Comment by kireevco** [comment] 2015-05-08 01:31
Im building crosstool-ng via https://github.com/pfalcon/esp-open-sdk with recurse option, so yes.
Thank you.

**Comment by bhundven** [comment] 2015-05-08 01:34
Sorry, I'm no good at tracking projects that use ct-ng. I also don't own any Microsoft based computers (yes, I live in Seattle), so you need to provide more info then the links you provided.

**Comment by kireevco** [comment] 2015-05-08 01:37
What kind of info would be required? all this repo does is get latest ct-ng and builds it in addition to other tools. I would appreciate some suggestions about how to troubleshoot this

```
zconf.tab.c: In function `zconfparse':
zconf.tab.c:1656: error: `kconf_id_strings' undeclared (first use in this functi
on)
```

Thank you.

**Comment by bhundven** [comment] 2015-10-14 22:22
@kireevco I've updated kconfig since. Can you try the latest master?

**Comment by kireevco** [comment] 2015-10-15 05:18
Cool, I will test and report back, thank you.

**Comment by bhundven** [comment] 2015-10-20 22:32
@kireevco Any update?

**Comment by kireevco** [comment] 2015-10-21 11:50
@bhundven I recreated my test environment.
I applied `sed -i 's/ESCDELAY = 1;/set_escdelay(1);/g' ./crosstool-NG/kconfig/nconf.c`
and I'm getting:
```
./configure --prefix=`pwd`
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking for a BSD-compatible install... /usr/bin//install -c
checking for grep that handles long lines and -e... /usr/bin//grep
checking for egrep... /usr/bin//grep -E
checking for a sed that does not truncate output... /usr/bin//sed
checking whether sed understands -r -i -e... yes
checking whether ln -s works... no, using cp -p
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking for gobjcopy... no
checking for objcopy... objcopy
checking for absolute path to objcopy... /usr/bin/objcopy.exe
checking for gobjdump... no
checking for objdump... objdump
checking for absolute path to objdump... /usr/bin/objdump.exe
checking for greadelf... no
checking for readelf... readelf
checking for absolute path to readelf... /usr/bin/readelf.exe
checking for gperf... gperf
checking for absolute path to gperf... /usr/bin/gperf.exe
checking for bison... bison
checking for flex... flex
checking for makeinfo... makeinfo
checking for cut... cut
checking for stat... stat
checking for readlink... readlink
checking for wget... wget
checking for tar... tar
checking for gzip... gzip
checking for bzip2... bzip2
checking for patch... /usr/bin//patch
checking for bash >= 3.1... /usr/bin//bash
checking for GNU awk... /usr/bin//gawk
checking for GNU make >= 3.80... /usr/bin//make
checking whether /usr/bin//make sets $(MAKE)... yes
checking for make 3.81... yes
checking for GNU libtool >= 1.5.26... /usr/bin//libtool
checking for GNU libtoolize >= 1.5.26... /usr/bin//libtoolize
checking for GNU automake >= 1.10... /usr/bin//automake
checking for xz... xz
checking for cvs... cvs
checking for svn... no
checking for inline... inline
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for size_t... yes
checking for working alloca.h... no
checking for alloca... yes
checking libintl.h usability... no
checking libintl.h presence... no
checking for libintl.h... no
checking ncurses/ncurses.h usability... no
checking ncurses/ncurses.h presence... no
checking for ncurses/ncurses.h... no
checking ncurses/curses.h usability... no
checking ncurses/curses.h presence... no
checking for ncurses/curses.h... no
checking ncursesw/curses.h usability... no
checking ncursesw/curses.h presence... no
checking for ncursesw/curses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for library containing initscr... -lncurses
configure: creating ./config.status
config.status: creating Makefile
make MAKELEVEL=0
make: Entering directory `/c/Users/User/packages/esp-open-sdk/windows/mignw/esp-
open-sdk/crosstool-NG'
  SED    'ct-ng'
  SED    'scripts/crosstool-NG.sh'
  SED    'scripts/saveSample.sh'
  SED    'scripts/showTuple.sh'
  GEN    'config/configure.in'
  GEN    'paths.mk'
  GEN    'paths.sh'
  DEP    'nconf.gui.dep'
  DEP    'nconf.dep'
  DEP    'lxdialog/yesno.dep'
  DEP    'lxdialog/util.dep'
  DEP    'lxdialog/textbox.dep'
  DEP    'lxdialog/menubox.dep'
  DEP    'lxdialog/inputbox.dep'
  DEP    'lxdialog/checklist.dep'
  DEP    'mconf.dep'
  DEP    'conf.dep'
  BISON  'zconf.tab.c'
  GPERF  'zconf.hash.c'
  LEX    'lex.zconf.c'
  DEP    'zconf.tab.dep'
  CC     'zconf.tab.o'
  CC     'conf.o'
  LD     'conf'
  CC     'lxdialog/checklist.o'
  CC     'lxdialog/inputbox.o'
  CC     'lxdialog/menubox.o'
  CC     'lxdialog/textbox.o'
  CC     'lxdialog/util.o'
  CC     'lxdialog/yesno.o'
  CC     'mconf.o'
  LD     'mconf'
  CC     'nconf.o'
nconf.c: In function `clean_items':
nconf.c:491: warning: passing arg 1 of `bzero' from incompatible pointer type
nconf.c:492: warning: passing arg 1 of `bzero' from incompatible pointer type
nconf.c: In function `item_make':
nconf.c:535: warning: passing arg 1 of `bzero' from incompatible pointer type
  CC     'nconf.gui.o'
  LD     'nconf'
nconf.o:nconf.c:(.text+0x3ca): undefined reference to `_strcasestr'
collect2: ld returned 1 exit status
make: *** [nconf] Error 1
make: *** [build-lib-kconfig] Error 2
make: *** [build] Error 2
make: Leaving directory `/c/Users/User/packages/esp-open-sdk/windows/mignw/esp-o
pen-sdk/crosstool-NG'
make[1]: *** [_ct-ng] Error 2
make[1]: Leaving directory `/c/Users/User/packages/esp-open-sdk/windows/mignw/es
p-open-sdk/crosstool-NG'
make: *** [crosstool-NG/ct-ng] Error 2
```

Any clue where to look?

**Comment by mingwandroid** [comment] 2015-10-21 13:14
@bhundven I think we need to be clear that mingw.org is deprecated in favour of MinGW-w64, after that, I have a series of patches that must be merged to make crosstool-ng workable on MSYS2/MinGW-w64. I'll get round to them ASAP (after Cygwin is working).

**Comment by kireevco** [comment] 2015-10-21 13:25
I just made it work. Two things:
I had to re-implement `strcasestr` and add it's prototype. Secondly I had to change `ESCDELAY = 1;` to `set_escdelay(1);`

```
make
  SED    'ct-ng'
  SED    'scripts/crosstool-NG.sh'
  SED    'scripts/saveSample.sh'
  SED    'scripts/showTuple.sh'
  GEN    'config/configure.in'
  GEN    'paths.mk'
  GEN    'paths.sh'
  DEP    'nconf.gui.dep'
  DEP    'nconf.dep'
  DEP    'lxdialog/yesno.dep'
  DEP    'lxdialog/util.dep'
  DEP    'lxdialog/textbox.dep'
  DEP    'lxdialog/menubox.dep'
  DEP    'lxdialog/inputbox.dep'
  DEP    'lxdialog/checklist.dep'
  DEP    'mconf.dep'
  DEP    'conf.dep'
  BISON  'zconf.tab.c'
  GPERF  'zconf.hash.c'
  LEX    'lex.zconf.c'
  DEP    'zconf.tab.dep'
  CC     'zconf.tab.o'
  CC     'conf.o'
  LD     'conf'
  CC     'lxdialog/checklist.o'
  CC     'lxdialog/inputbox.o'
  CC     'lxdialog/menubox.o'
  CC     'lxdialog/textbox.o'
  CC     'lxdialog/util.o'
  CC     'lxdialog/yesno.o'
  CC     'mconf.o'
  LD     'mconf'
  CC     'nconf.o'
nconf.c: In function `clean_items':
nconf.c:493: warning: passing arg 1 of `bzero' from incompatible pointer type
nconf.c:494: warning: passing arg 1 of `bzero' from incompatible pointer type
nconf.c: In function `item_make':
nconf.c:537: warning: passing arg 1 of `bzero' from incompatible pointer type
nconf.c:1579:2: warning: no newline at end of file
  CC     'nconf.gui.o'
  LD     'nconf'
  SED    'docs/ct-ng.1'
  GZIP   'docs/ct-ng.1.gz'
```

I'll confirm if it actually works with building my xtensa toolcahin

**Comment by kireevco** [comment] 2015-10-21 13:32
Now my question is, how would I get a case-sensitive filesystem under my mingw?
(in cygwin I could've mingled with fstab)

**Comment by mingwandroid** [comment] 2015-10-21 13:40
From https://cygwin.com/cygwin-ug-net/using-specialnames.html in the "Case sensitive filenames" you'll see that in general for a native Win32 program, you have to put up with case insensitivity.

Thing is, your build system is Cygwin-derived; either Cygwin, MSYS or MSYS2, so you can get all the way to creating a tarball with case sensitive filenames (not sure about MSYS here, again, it's too old for me to care about). The only problem will be when you attempt to use those files with clashing case. In the Linux kernel, these exist only in netfilter. So unless you try to include those headers because you are using the netfilter API, you shouldn't have any problems. AFAIK, the netfilter stuff is deprecated too.

**Comment by kireevco** [comment] 2015-10-21 15:20
MinGW is not cygwin and doesn't do POSIX emulation. There is no such thing as fstab, for instance.
On cygwin you can just mount it on mingw you can't.

**Comment by mingwandroid** [comment] 2015-10-21 15:37
I think you must've misunderstood my comment?

If you use case-sensitive Cygwin (or one of its derivative projects) to build crosstool-ng compilers nad Cygwin tar/xz to compress those files, you'd end up with Linux headers in a tarball that have files with cases that clash in include/netfilter.

If you then try to use those "i686-pc-mingw32" binaries (though in all honesty you'd be better off using {i686,x86_64}-w64-mingw32" as your host(s)) which use the Win32 API exclusively for file IO and try to compile code that includes netfilter headers then those compilers will include the wrong file about 50% of the time.

**Comment by kireevco** [comment] 2015-10-21 15:42
yeah, I probably misread.
Then, what's my option then?

**Comment by mingwandroid** [comment] 2015-10-21 15:48
Advise people not to attempt to *use* your cross compilers to build anything that needs to call the netfilter API?

It's deprecated and probably not of much interest to your users anyway.

**Comment by kireevco** [comment] 2015-10-21 16:16
Well, I don't think esp-open-sdk uses netfilter... anyway, thank you. I'll build a cygwin environment with {i686,x86_64}-w64-mingw32 and sounds like that should work fine .

**Comment by mingwandroid** [comment] 2015-10-21 16:40
It will work fine when I get a chance to finish the patches and Bryan a chance to review them! It'll be a few days yet I'm afraid.

**Comment by Juppit** [comment] 2015-11-11 07:22
@kireevco youcan change a value in the windows registry (my system win8/64) like:
# go to regedit and change the value obcaseinsensitive from 1 to 0 in:
# HKEY_LOCAL_MASCHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel

**Comment by kireevco** [comment] 2015-11-11 07:24
@Juppit I already passed this stage. You also need to change / to posix in `/etc/fstab`. Can you please share a build script with environment config or maybe contribute to [kireevco/packages/cygwin](https://github.com/kireevco/packages/tree/master/esp-open-sdk/windows/cygwin) ?

**Comment by Juppit** [comment] 2015-11-11 08:04
I have already spent months unsuccessfully.
My plan was just to program ESP8266, and there I found @igrr and: voilà!

Do you know Japanese? No? No matter:
http://blog.techlab-xe.net/archives/3274

On 11.11.2015 at 08:24 wrote Dmitry Kireev:

**Comment by kireevco** [comment] 2015-11-11 08:45
@Juppit I already applied all those patches and added other things. Crosstool-ng builds fine https://github.com/kireevco/packages/blob/master/esp-open-sdk/windows/cygwin/20-build_cygwin.sh.

**Comment by Juppit** [comment] 2015-11-11 11:17
I'll give you my comments, but I do not know where, here it will be off topic

**Comment by mingwandroid** [comment] 2015-11-11 12:43
For the avoidance of doubt, we removed support for mingw.org in favour of mingw-w64 and will continue this course of action in order to simplify the support requirements. mingw.org does not support 64-bit and has a less active community around it.

**Comment by mingwandroid** [comment] 2015-11-13 11:21
This should be fixed now. I will wait until the 1.22 release to close.

**Comment by mingwandroid** [comment] 2015-11-14 11:14
This is fixed, but you must follow the documentation at:

https://github.com/crosstool-ng/crosstool-ng/blob/master/docs/C%20-%20Misc.%20tutorials.txt#L317-L361

**Closed by mingwandroid** 2015-11-14 11:14 UTC
Labels: bug

**Comment by mlt** [comment] 2016-03-18 06:34
Is it a regression? I tried to build current *master* with mingw-w64 on msys2, but I'm getting same problems. First it stopped on 00316d987557a96bfd5239c87963b7ad1e3c42bd  , but I set `/mingw64/include/ncurses`, but then I get
```
  GPERF  'zconf.hash.c'
  LEX    'zconf.lex.c'
(standard input):14: warning: junk after %% is ignored
, defaulting to Cage option ANSI-C
(standard input):5: junk after declaration
  DEP    'zconf.tab.dep'
  CC     'zconf.tab.o'
  CC     'conf.o'
  CC     'lxdialog/checklist.o'
  CC     'lxdialog/inputbox.o'
zconf.tab.c: In function 'zconfparse':
zconf.tab.c:1511:42: error: 'kconf_id_strings' undeclared (first use in this function)
  zconf_error("unexpected option \"%s\"", kconf_id_strings + (yyvsp[-2].id)->name);
```
Somehow `zconf.hash.c` is empty.

**Comment by kireevco** [comment] 2016-03-18 06:46
You can't build on mingw, you have to use Cygwin, from what I understand. I gave up on crosstool, using my own script.
