### ISSUE TITLE
ld: library not found for -lcrt0.o

### ISSUE THREAD

**Issue by pzg250** [crosstool-ng/crosstool-ng#31] opened 2015-01-12 06:25 UTC
Hi,
I met this error during compiling the example "arm-unknown-linux-gnueabi".
I have searched some info from internet. One of the suggestion is to install Xcode tools. But i have installed the Xcode tools.. Anyone can help ? 

ENV: mac os X 10.10.1
Here is the part of my logs.

[DEBUG]  Checking that gcc can compile a trivial statically linked program (CT_WANTS_STATIC_LINK)
[DEBUG]    You may need to ensure that static libraries such as libc.a are installed on your system
[DEBUG]    ==> Executing: 'x86_64-build_apple-darwin14.0.0-gcc' '-O2' '-g' '-pipe' '/Volumes/pri-eabi/.build/arm-unknown-linux-gnueabi/build/test.c' '-static' '-o' '/Volumes/pri-eabi/.build/arm-unknown-linux-gnueabi/build/.gccout' 
[DEBUG]    ld: library not found for -lcrt0.o
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Checking that gcc can compile a trivial statically linked program (CT_WANTS_STATIC_LINK)'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@546]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/crosstool-ng/share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]

**Comment by bhundven** [comment] 2015-01-24 19:22
@pzg250 Static linking does not work on mac os x with the llvm/clang gcc.
If you use a gcc from homebrew/macports, and use that to build a statically linked toolchain on mac os x, then that will work.
If you are not building a statically linked toolchain, make sure you're not enabling static libstdc++ in the compiler settings.

**Comment by pzg250** [comment] 2015-01-25 03:57
Hi Bhundven,
Thanks very much for your help. I will try the second method.
About the first method, i think i have installed the gcc from homebrew, how do i set the default compiler to gcc from homebrew but not clang gcc ?

Regards,
Major

**Comment by bhundven** [comment] 2015-01-25 04:18
@pzg250 your $PATH dictates the compiler that is used. The items separated by ':' are evaluated in order.

```echo $PATH```

Hence, making the directory that the default compiler first in that order will be executed first.

**Comment by pzg250** [comment] 2015-01-26 00:16
@bhundven Thanks very much.

**Comment by pzg250** [comment] 2015-01-26 09:20
Hi @bhundven ,
During the build, i met another issue that shows some tarballs cannot be downloaded.
Have you seen this error before ? Thanks

[EXTRA]  Dumping internal crosstool-NG configuration: done in 1.00s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'linux-3.15.4'
[EXTRA]    Saving 'linux-3.15.4.tar.xz' to local storage
[EXTRA]    Retrieving 'gmp-5.1.3'
[EXTRA]    Saving 'gmp-5.1.3.tar.xz' to local storage
[EXTRA]    Retrieving 'mpfr-3.1.2'
[EXTRA]    Saving 'mpfr-3.1.2.tar.xz' to local storage
[EXTRA]    Retrieving 'isl-0.12.2'
[EXTRA]    Saving 'isl-0.12.2.tar.bz2' to local storage
[EXTRA]    Retrieving 'cloog-0.18.1'
[EXTRA]    Saving 'cloog-0.18.1.tar.gz' to local storage
[EXTRA]    Retrieving 'mpc-1.0.2'
[EXTRA]    Saving 'mpc-1.0.2.tar.gz' to local storage
[EXTRA]    Retrieving 'libelf-0.8.13'
[EXTRA]    Saving 'libelf-0.8.13.tar.gz' to local storage
[EXTRA]    Retrieving 'binutils-2.22'
[EXTRA]    Saving 'binutils-2.22.tar.bz2' to local storage
[EXTRA]    Retrieving 'gcc-4.9.1'
[79:59] \ /usr/local/crosstool-ng/lib/ct-ng.1.20.0/scripts/functions: line 216: 18389 Segmentation fault: 11  "${@}" 2>&1
     18390 Done                    | CT_DoLog "${level}"
[87:57] \ /usr/local/crosstool-ng/lib/ct-ng.1.20.0/scripts/functions: line 216: 18465 Segmentation fault: 11  "${@}" 2>&1
     18466 Done                    | CT_DoLog "${level}"
[EXTRA]    Saving 'gcc-4.9.1' to local storage
[EXTRA]    Retrieving 'glibc-2.19'
[118:27] / /usr/local/crosstool-ng/lib/ct-ng.1.20.0/scripts/functions: line 216: 19218 Segmentation fault: 11  "${@}" 2>&1
     19219 Done                    | CT_DoLog "${level}"
[ERROR]  / 
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_libc_get[scripts/build/libc/glibc.sh@741]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@586]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/crosstool-ng/share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]  / 
[ERROR]  (elapsed: 122:28.00)
[122:28] / make: *** [build] Error 1

**Comment by bhundven** [comment] 2015-01-26 15:59
Hmm, are you using the latest from git or are you using the 1.20.0 release?
Also, which version of bash are you using:
```bash --version```

**Comment by pzg250** [comment] 2015-01-27 00:24
@bhundven I am using the 1.20.0 release. And the bash version shows as below.

GNU bash, version 4.3.30(1)-release (x86_64-apple-darwin14.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by bhundven** [comment] 2015-01-27 02:13
I've seen one other issue just like this, also on Mac OS X.
Could you post the full build log somewhere and link here?

**Comment by pzg250** [comment] 2015-01-27 04:54
@bhundven Hi, I am just sent the bull log to your gmail. Thanks

**Comment by bhundven** [comment] 2015-01-28 00:20
@pzg250 Hrm, I haven't received anything yet. Sure you got the right email address?

**Comment by pzg250** [comment] 2015-01-28 01:43
@bhundven Hi, can you access below link ? 
https://app.box.com/s/9hf7slga5i7raj69vcn1pa3g4yin2uro
Regards,

**Comment by bhundven** [comment] 2015-01-30 21:37
Interesting that I don't see the segmentation fault in the log, but what I do see is ct-ng not being able to get glibc-2.19. I'm going to do some testing.

**Comment by bhundven** [comment] 2015-02-18 05:26
I can't reproduce this issue.
Copy the results of ```echo $PATH``` and ```brew info bash``` to a gist and link here.

**Comment by muellermartin** [comment] 2015-03-18 14:53
I do not get the segfault, but I'm also not getting crosstool-ng to use homebrew's GCC instead of LLVM/Clang therefore I can't build a statically linked libstdc++. Any updates on this?

**Comment by bhundven** [comment] 2015-03-18 20:28
As it currently stands, static libstdc++, static toolchain, and/or static anything is not supported on Mac OS X.

**Comment by bhundven** [comment] 2015-06-01 16:30
On top of the fact that:
1. I cannot reproduce this, as my mac is broken.
2. Building static binaries on mac os x is unsupported.
3. You can build static binaries on mac os x, in an unsupported way (yes, I'm somewhat conflicting here, but both say: unsupported)
4. I don't support unsupported methods

I'm closing this issue as known issue and wontfix.
We'll get back to this issue in a later version of ct-ng, hence why it is marked as known issue.
Expect me to reopen this at a later date.

**Closed by bhundven** 2015-06-01 16:30 UTC
Labels: known issue, wontfix

**Comment by xs23933** [comment] 2015-12-23 06:22
u can change
/usr/local/Cellar/crosstool-ng/1.21.0/lib/ct-ng.1.21.0/scripts/crosstool-NG.sh
 find -static to -Bstatic

**Comment by xs23933** [comment] 2015-12-23 06:28
if u need ginstall u can link install
ln -s /usr/bin/install /usr/local/bin/ginstall

**Comment by wagnersilveria** [comment] 2016-06-13 15:31
Any update on this?
