### ISSUE TITLE
Build failed in step 'Installing automake for build'

### ISSUE THREAD

**Issue by amith-c2a** [crosstool-ng/crosstool-ng#987] opened 2018-06-12 11:30 UTC
Version: crosstool-ng-1.23.0
OS: Linux ubuntu 4.15.0-22-generic (Ubuntu 18.04)
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/2093766/config.zip)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2093996/build.log)

I saw similar issue, but as you can see, in my case the error number is 2.

```[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20180612.141956
[INFO ]  Building environment variables
[WARN ]  Directory '/home/amit/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = arm-unknown-linux-uclibcgnueabi
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.18s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 0.14s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[INFO ]  Extracting and patching toolchain components: done in 0.24s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Installing autoconf for build
[EXTRA]    Configuring autoconf
[EXTRA]    Building autoconf
[EXTRA]    Installing autoconf
[INFO ]  Installing autoconf for build: done in 4.47s (at 00:07)
[INFO ]  =================================================================
[INFO ]  Installing automake for build
[EXTRA]    Configuring automake
[EXTRA]    Building automake
[ERROR]    make[1]: *** [doc/automake-1.15.1] Error 255
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing automake for build'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_automake_backend[scripts/build/companion_tools/300-automake.sh@46]
[ERROR]  >>        called from: do_companion_tools_automake_for_build[scripts/build/companion_tools/300-automake.sh@17]
[ERROR]  >>        called from: do_companion_tools_for_build[scripts/build/companion_tools.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.23.0/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 0:10.14)
[00:11] / /usr/local/bin/ct-ng:147: recipe for target 'build' failed
make: *** [build] Error 2```

**Comment by Floessie** [comment] 2018-06-12 11:42
Take a look at the `build.log` file inside your current build directory. There you'll find the details on what went wrong near the end of the file.

HTH,
Flössie

**Comment by amith-c2a** [comment] 2018-06-12 12:38
I added the `build.log` file. It's huge and I could not find what's wrong from it.
Can you point out the problem please?

**Comment by stilor** [comment] 2018-06-12 16:10
This is the error but I don't know why help2man didn't like the `automake --help` output on your machine.

````
[ALL  ]    help2man: can't get `--help' info from automake-1.15
[ALL  ]    Try `--no-discard-stderr' if option outputs to stderr
[ALL  ]    Makefile:3687: recipe for target 'doc/automake-1.15.1' failed
[ERROR]    make[1]: *** [doc/automake-1.15.1] Error 255
````

**Comment by Floessie** [comment] 2018-06-12 16:16
This is a duplicate of #973. The hint over there that it has something to do with the Perl installed seems to be a good one...

**Comment by stilor** [comment] 2018-09-29 20:57
Ok, what is the version of Perl on the host?

**Comment by stilor** [comment] 2018-09-29 22:28
1.15.1 already has a fix. Backported to 1.14.1 and 1.11.6.

**Closed** 2018-09-29 22:31 UTC
