### ISSUE TITLE
CT_ARCH_ARM_MODE_THUMB not set, but newlib contains some Thumb functions anyway

### ISSUE THREAD

**Issue by SolraBizna** [crosstool-ng/crosstool-ng#499] opened 2016-12-07 18:27 UTC
I'm targeting an ARM platform that doesn't support Thumb, but otherwise supports ARMv7a. CT_ARCH_ARM_MODE_THUMB is not set in config, and _most_ of newlib correctly built without using Thumb, but some functions are Thumb anyway, including `strlen` and `memchr`.

I'm fairly sure this is an upstream bug, but not completely sure. And I can't do much deeper investigation right now; I'm currently putting my workstation back together after btrfs threw a tantrum.

**Comment by stilor** [comment] 2016-12-07 18:43
Can you post your config?

**Comment by SolraBizna** [comment] 2016-12-08 01:15
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/638170/config.txt)

Fortunately, I can work around the problem by providing my own implementations of the few faulty functions.

**Comment by stilor** [comment] 2017-02-11 06:03
Well, I confirmed that it is indeed a newlib issue - they include strlen() implementation from strlen-thumb2-Os.S even if the current mode is not Thumb. My knowledge on ARM interworking is a bit rusty, but GCC's manual says in the description of `-mthumb-interwork` (emphasis mine):

"Generate code that supports calling between the ARM and Thumb instruction sets.  Without this option, **on pre-v5 architectures**, the two instruction sets cannot be reliably used inside one program."

So it looks like newlib is relying on all architectures from v5 and up to support Thumb without any extra interworking needed, and proceeds to generate Thumb versions of the routines where it saves a few bytes. If you platform is special in that respect, I think you need to discuss its support with newlib developers.

Closing the issue here.

**Closed by stilor** 2017-02-11 06:03 UTC
