### ISSUE TITLE
newlib does not support *-*-eabihf

### ISSUE THREAD

**Issue by gosfon** [crosstool-ng/crosstool-ng#206] opened 2015-10-13 06:02 UTC
Hello, I used the crosstool-ng with updated master branch (adad9c2b859) git source code to build toolchains for arm-unknown-eabi, and got through Installing pass-2 core C gcc but stoped by error in step 'Installing C library'.

I google for days and do some effort, but still build failed today and cannot got an effective approach. Help me please!

##### Here's the error messages:
```
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20151013.115413
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = i686-pc-linux-gnu
[EXTRA]      host   = i686-pc-linux-gnu
[EXTRA]      target = arm-rpi-eabihf
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.13s (at 00:05)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 0.27s (at 00:05)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'gmp-6.0.0a'
[EXTRA]    Patching 'gmp-6.0.0a'
[EXTRA]    Extracting 'mpfr-3.1.3'
[EXTRA]    Patching 'mpfr-3.1.3'
[EXTRA]    Extracting 'isl-0.14'
[EXTRA]    Patching 'isl-0.14'
[EXTRA]    Extracting 'mpc-1.0.3'
[EXTRA]    Patching 'mpc-1.0.3'
[EXTRA]    Extracting 'binutils-2.25.1'
[EXTRA]    Patching 'binutils-2.25.1'
[EXTRA]    Extracting 'gcc-5.2.0'
[EXTRA]    Patching 'gcc-5.2.0'
[EXTRA]    Extracting 'newlib-2.2.0'
[EXTRA]    Patching 'newlib-2.2.0'
[EXTRA]    Extracting 'gdb-7.10'
[EXTRA]    Patching 'gdb-7.10'
[EXTRA]    Extracting 'strace-4.10'
[EXTRA]    Patching 'strace-4.10'
[INFO ]  Extracting and patching toolchain components: done in 130.39s (at 02:16)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 59.59s (at 03:15)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 44.08s (at 03:59)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[EXTRA]    Configuring ISL
[EXTRA]    Building ISL
[EXTRA]    Installing ISL
[INFO ]  Installing ISL for host: done in 44.89s (at 04:44)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 22.55s (at 05:07)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 107.16s (at 06:54)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]  Installing C library headers & start files: done in 0.04s (at 06:54)
[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[INFO ]  Installing pass-2 core C gcc compiler: done in 742.27s (at 19:16)
[INFO ]  =================================================================
[INFO ]  Installing C library
[EXTRA]    Configuring C library
[EXTRA]    Building C library
[EXTRA]    Installing C library
[ERROR]    gmake[4]: *** [install-linux] Error 1
[ERROR]    gmake[3]: *** [install] Error 2
[ERROR]    gmake[2]: *** [install-target-libgloss] Error 2
[ERROR]    gmake[1]: *** [install] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_libc[scripts/build/libc/newlib.sh@136]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/build-tools-ng/result/crosstool-ng-master/share/doc/crosstool-ng//B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 20:13.78)
```

##### Here's the build log messages:
```
[ALL  ]    gmake[4]: Entering directory '/home/build-tools-ng/build/ct-ng/.build/arm-rpi-eabihf/build/build-libc/arm-rpi-eabihf/libgloss/arm'
[ALL  ]    /home/build-tools-ng/build/ct-ng/.build/tools/bin/install -c -m 644 crt0.o /home/build-tools-ng/result/x-tools/arm-rpi-eabihf/arm-rpi-eabihf/lib/$x
[ALL  ]    set -e; for x in linux-crt0.o libgloss-linux.a; do /home/build-tools-ng/build/ct-ng/.build/tools/bin/install -c -m 644 $x /home/build-tools-ng/result/x-tools/arm-rpi-eabihf/arm-rpi-eabihf/lib/$x; done
[ALL  ]    set -e; for x in linux.specs; do /home/build-tools-ng/build/ct-ng/.build/tools/bin/install -c -m 644 /home/build-tools-ng/build/ct-ng/.build/src/newlib-2.2.0/libgloss/arm/$x /home/build-tools-ng/result/x-tools/arm-rpi-eabihf/arm-rpi-eabihf/lib/$x; done
[ALL  ]    /usr/bin/install: cannot stat '/home/build-tools-ng/build/ct-ng/.build/src/newlib-2.2.0/libgloss/arm/linux.specs': No such file or directory
[ALL  ]    Makefile:226: recipe for target 'install-linux' failed
[ERROR]    gmake[4]: *** [install-linux] Error 1
[ALL  ]    gmake[4]: Leaving directory '/home/build-tools-ng/build/ct-ng/.build/arm-rpi-eabihf/build/build-libc/arm-rpi-eabihf/libgloss/arm'
[ALL  ]    Makefile:143: recipe for target 'install' failed
[ERROR]    gmake[3]: *** [install] Error 2
[ALL  ]    gmake[3]: Leaving directory '/home/build-tools-ng/build/ct-ng/.build/arm-rpi-eabihf/build/build-libc/arm-rpi-eabihf/libgloss'
[ALL  ]    Makefile:8473: recipe for target 'install-target-libgloss' failed
[ERROR]    gmake[2]: *** [install-target-libgloss] Error 2
[ALL  ]    gmake[2]: Leaving directory '/home/build-tools-ng/build/ct-ng/.build/arm-rpi-eabihf/build/build-libc'
[ALL  ]    Makefile:2149: recipe for target 'install' failed
[ERROR]    gmake[1]: *** [install] Error 2
[ALL  ]    gmake[1]: Leaving directory '/home/build-tools-ng/build/ct-ng/.build/arm-rpi-eabihf/build/build-libc'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_libc[scripts/build/libc/newlib.sh@136]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/build-tools-ng/result/crosstool-ng-master/share/doc/crosstool-ng//B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 20:13.78)
```

##### Here's my .config of ct-ng:
```
#
# Automatically generated file; DO NOT EDIT.
# Crosstool-NG Configuration
#
CT_CONFIGURE_has_xz=y
CT_CONFIGURE_has_cvs=y
CT_CONFIGURE_has_svn=y
CT_MODULES=y

#
# Paths and misc options
#

#
# crosstool-NG behavior
#
# CT_OBSOLETE is not set
# CT_EXPERIMENTAL is not set
# CT_DEBUG_CT is not set

#
# Paths
#
CT_LOCAL_TARBALLS_DIR="/mnt/hgfs/Csrc"
CT_SAVE_TARBALLS=y
CT_WORK_DIR="${CT_TOP_DIR}/.build"
CT_PREFIX_DIR="/home/build-tools-ng/result/x-tools/${CT_TARGET}"
CT_INSTALL_DIR="${CT_PREFIX_DIR}"
CT_RM_RF_PREFIX_DIR=y
CT_REMOVE_DOCS=y
CT_INSTALL_DIR_RO=y
CT_STRIP_ALL_TOOLCHAIN_EXECUTABLES=y

#
# Downloading
#
# CT_FORBID_DOWNLOAD is not set
# CT_FORCE_DOWNLOAD is not set
CT_CONNECT_TIMEOUT=10
# CT_ONLY_DOWNLOAD is not set
# CT_USE_MIRROR is not set

#
# Extracting
#
# CT_FORCE_EXTRACT is not set
CT_OVERIDE_CONFIG_GUESS_SUB=y
# CT_ONLY_EXTRACT is not set
CT_PATCH_BUNDLED=y
# CT_PATCH_LOCAL is not set
# CT_PATCH_BUNDLED_LOCAL is not set
# CT_PATCH_LOCAL_BUNDLED is not set
# CT_PATCH_BUNDLED_FALLBACK_LOCAL is not set
# CT_PATCH_LOCAL_FALLBACK_BUNDLED is not set
# CT_PATCH_NONE is not set
CT_PATCH_ORDER="bundled"

#
# Build behavior
#
CT_PARALLEL_JOBS=8
CT_LOAD=""
CT_USE_PIPES=y
CT_EXTRA_CFLAGS_FOR_BUILD=""
CT_EXTRA_LDFLAGS_FOR_BUILD=""
CT_EXTRA_CFLAGS_FOR_HOST=""
CT_EXTRA_LDFLAGS_FOR_HOST=""
# CT_CONFIG_SHELL_SH is not set
# CT_CONFIG_SHELL_ASH is not set
CT_CONFIG_SHELL_BASH=y
# CT_CONFIG_SHELL_CUSTOM is not set
CT_CONFIG_SHELL="${bash}"

#
# Logging
#
# CT_LOG_ERROR is not set
# CT_LOG_WARN is not set
# CT_LOG_INFO is not set
CT_LOG_EXTRA=y
# CT_LOG_ALL is not set
# CT_LOG_DEBUG is not set
CT_LOG_LEVEL_MAX="EXTRA"
# CT_LOG_SEE_TOOLS_WARN is not set
CT_LOG_PROGRESS_BAR=y
CT_LOG_TO_FILE=y
CT_LOG_FILE_COMPRESS=y

#
# Target options
#
CT_ARCH="arm"
CT_ARCH_SUPPORTS_BOTH_MMU=y
CT_ARCH_SUPPORTS_BOTH_ENDIAN=y
CT_ARCH_SUPPORTS_32=y
CT_ARCH_SUPPORTS_64=y
CT_ARCH_SUPPORTS_WITH_ARCH=y
CT_ARCH_SUPPORTS_WITH_CPU=y
CT_ARCH_SUPPORTS_WITH_TUNE=y
CT_ARCH_SUPPORTS_WITH_FLOAT=y
CT_ARCH_SUPPORTS_WITH_FPU=y
CT_ARCH_SUPPORTS_SOFTFP=y
CT_ARCH_DEFAULT_HAS_MMU=y
CT_ARCH_DEFAULT_LE=y
CT_ARCH_DEFAULT_32=y
CT_ARCH_CPU="arm1176jzf-s"
CT_ARCH_FPU="vfp"
# CT_ARCH_BE is not set
CT_ARCH_LE=y
CT_ARCH_32=y
# CT_ARCH_64 is not set
CT_ARCH_BITNESS=32
CT_ARCH_FLOAT_HW=y
# CT_ARCH_FLOAT_SW is not set
CT_TARGET_CFLAGS=""
CT_TARGET_LDFLAGS=""
# CT_ARCH_alpha is not set
CT_ARCH_arm=y
# CT_ARCH_avr is not set
# CT_ARCH_avr32 is not set
# CT_ARCH_blackfin is not set
# CT_ARCH_m68k is not set
# CT_ARCH_mips is not set
# CT_ARCH_nios2 is not set
# CT_ARCH_powerpc is not set
# CT_ARCH_s390 is not set
# CT_ARCH_sh is not set
# CT_ARCH_sparc is not set
# CT_ARCH_x86 is not set
CT_ARCH_alpha_AVAILABLE=y
CT_ARCH_arm_AVAILABLE=y
CT_ARCH_avr_AVAILABLE=y
CT_ARCH_avr32_AVAILABLE=y
CT_ARCH_blackfin_AVAILABLE=y
CT_ARCH_m68k_AVAILABLE=y
CT_ARCH_microblaze_AVAILABLE=y
CT_ARCH_mips_AVAILABLE=y
CT_ARCH_nios2_AVAILABLE=y
CT_ARCH_powerpc_AVAILABLE=y
CT_ARCH_s390_AVAILABLE=y
CT_ARCH_sh_AVAILABLE=y
CT_ARCH_sparc_AVAILABLE=y
CT_ARCH_x86_AVAILABLE=y
CT_ARCH_SUFFIX=""

#
# Generic target options
#
# CT_MULTILIB is not set
CT_ARCH_USE_MMU=y
CT_ARCH_ENDIAN="little"

#
# Target optimisations
#
# CT_ARCH_FLOAT_AUTO is not set
# CT_ARCH_FLOAT_SOFTFP is not set
CT_ARCH_FLOAT="hard"

#
# arm other options
#
CT_ARCH_ARM_MODE="arm"
CT_ARCH_ARM_MODE_ARM=y
# CT_ARCH_ARM_MODE_THUMB is not set
# CT_ARCH_ARM_INTERWORKING is not set
CT_ARCH_ARM_EABI_FORCE=y
CT_ARCH_ARM_EABI=y
CT_ARCH_ARM_TUPLE_USE_EABIHF=y

#
# Toolchain options
#

#
# General toolchain options
#
CT_FORCE_SYSROOT=y
CT_USE_SYSROOT=y
CT_SYSROOT_NAME="sysroot"
CT_SYSROOT_DIR_PREFIX=""
CT_WANTS_STATIC_LINK=y
# CT_STATIC_TOOLCHAIN is not set
CT_TOOLCHAIN_PKGVERSION="rpi B+"
CT_TOOLCHAIN_BUGURL=""

#
# Tuple completion and aliasing
#
CT_TARGET_VENDOR="rpi"
CT_TARGET_ALIAS_SED_EXPR=""
CT_TARGET_ALIAS=""

#
# Toolchain type
#
CT_CROSS=y
# CT_CANADIAN is not set
CT_TOOLCHAIN_TYPE="cross"

#
# Build system
#
CT_BUILD=""
CT_BUILD_PREFIX=""
CT_BUILD_SUFFIX=""

#
# Misc options
#
# CT_TOOLCHAIN_ENABLE_NLS is not set

#
# Operating System
#
CT_BARE_METAL=y
CT_KERNEL="bare-metal"
CT_KERNEL_bare_metal=y
# CT_KERNEL_linux is not set
CT_KERNEL_bare_metal_AVAILABLE=y
CT_KERNEL_linux_AVAILABLE=y
CT_KERNEL_windows_AVAILABLE=y

#
# Common kernel options
#

#
# Binary utilities
#
CT_ARCH_BINFMT_ELF=y
CT_BINUTILS="binutils"
CT_BINUTILS_binutils=y

#
# GNU binutils
#
CT_CC_BINUTILS_SHOW_LINARO=y
CT_BINUTILS_V_2_25_1=y
# CT_BINUTILS_LINARO_V_2_25 is not set
# CT_BINUTILS_V_2_25 is not set
# CT_BINUTILS_LINARO_V_2_24 is not set
# CT_BINUTILS_V_2_24 is not set
# CT_BINUTILS_V_2_23_2 is not set
# CT_BINUTILS_V_2_23_1 is not set
# CT_BINUTILS_V_2_22 is not set
# CT_BINUTILS_V_2_21_53 is not set
# CT_BINUTILS_V_2_21_1a is not set
# CT_BINUTILS_V_2_20_1a is not set
# CT_BINUTILS_V_2_19_1a is not set
# CT_BINUTILS_V_2_18a is not set
CT_BINUTILS_VERSION="2.25.1"
CT_BINUTILS_2_25_1_or_later=y
CT_BINUTILS_2_25_or_later=y
CT_BINUTILS_2_24_or_later=y
CT_BINUTILS_2_23_or_later=y
CT_BINUTILS_2_22_or_later=y
CT_BINUTILS_2_21_or_later=y
CT_BINUTILS_2_20_or_later=y
CT_BINUTILS_2_19_or_later=y
CT_BINUTILS_2_18_or_later=y
CT_BINUTILS_HAS_HASH_STYLE=y
CT_BINUTILS_HAS_GOLD=y
CT_BINUTILS_GOLD_SUPPORTS_ARCH=y
CT_BINUTILS_HAS_PLUGINS=y
CT_BINUTILS_HAS_PKGVERSION_BUGURL=y
CT_BINUTILS_LINKER_LD=y
# CT_BINUTILS_LINKER_GOLD is not set
# CT_BINUTILS_LINKER_LD_GOLD is not set
# CT_BINUTILS_LINKER_GOLD_LD is not set
CT_BINUTILS_LINKERS_LIST="ld"
CT_BINUTILS_LINKER_DEFAULT="bfd"
# CT_BINUTILS_PLUGINS is not set
CT_BINUTILS_EXTRA_CONFIG_ARRAY=""

#
# binutils other options
#

#
# C-library
#
CT_LIBC="newlib"
CT_LIBC_VERSION="2.2.0"
CT_LIBC_newlib=y
# CT_LIBC_none is not set
CT_LIBC_avr_libc_AVAILABLE=y
CT_LIBC_glibc_AVAILABLE=y
CT_THREADS="none"
CT_LIBC_mingw_AVAILABLE=y
CT_LIBC_musl_AVAILABLE=y
CT_LIBC_newlib_AVAILABLE=y
CT_CC_NEWLIB_SHOW_LINARO=y
# CT_LIBC_NEWLIB_LINARO_V_2_2_0 is not set
CT_LIBC_NEWLIB_V_2_2_0=y
# CT_LIBC_NEWLIB_LINARO_V_2_1_0 is not set
# CT_LIBC_NEWLIB_V_2_1_0 is not set
# CT_LIBC_NEWLIB_V_2_0_0 is not set
# CT_LIBC_NEWLIB_V_1_20_0 is not set
# CT_LIBC_NEWLIB_V_1_19_0 is not set
# CT_LIBC_NEWLIB_V_1_18_0 is not set
# CT_LIBC_NEWLIB_V_1_17_0 is not set
CT_LIBC_NEWLIB_2_2=y
CT_LIBC_NEWLIB_2_2_or_later=y
CT_LIBC_NEWLIB_2_1_or_later=y
CT_LIBC_NEWLIB_2_0_or_later=y
CT_LIBC_NEWLIB_TARGET_CFLAGS=""

#
# Architecture specific options
#
CT_LIBC_none_AVAILABLE=y
CT_LIBC_uClibc_AVAILABLE=y
CT_LIBC_SUPPORT_THREADS_NONE=y
CT_LIBC_PROVIDES_CXA_ATEXIT=y

#
# Common C library options
#
CT_THREADS_NONE=y

#
# newlib other options
#
CT_LIBC_NEWLIB_IO_C99FMT=y
CT_LIBC_NEWLIB_IO_LL=y
CT_LIBC_NEWLIB_IO_FLOAT=y
# CT_LIBC_NEWLIB_IO_LDBL is not set
CT_LIBC_NEWLIB_DISABLE_SUPPLIED_SYSCALLS=y
CT_LIBC_NEWLIB_ENABLE_TARGET_OPTSPACE=y
CT_LIBC_NEWLIB_EXTRA_CONFIG_ARRAY=""

#
# C compiler
#
CT_CC="gcc"
CT_CC_CORE_PASS_2_NEEDED=y
CT_CC_gcc=y
CT_CC_GCC_SHOW_LINARO=y
CT_CC_GCC_V_5_2_0=y
# CT_CC_GCC_V_5_1_0 is not set
# CT_CC_GCC_V_linaro_4_9 is not set
# CT_CC_GCC_V_4_9_3 is not set
# CT_CC_GCC_V_4_9_2 is not set
# CT_CC_GCC_V_4_9_1 is not set
# CT_CC_GCC_V_4_9_0 is not set
# CT_CC_GCC_V_linaro_4_8 is not set
# CT_CC_GCC_V_4_8_5 is not set
# CT_CC_GCC_V_4_8_4 is not set
# CT_CC_GCC_V_4_8_3 is not set
# CT_CC_GCC_V_4_8_2 is not set
# CT_CC_GCC_V_4_8_1 is not set
# CT_CC_GCC_V_4_8_0 is not set
# CT_CC_GCC_V_linaro_4_7 is not set
# CT_CC_GCC_V_4_7_4 is not set
# CT_CC_GCC_V_4_7_3 is not set
# CT_CC_GCC_V_4_7_2 is not set
# CT_CC_GCC_V_4_7_1 is not set
# CT_CC_GCC_V_4_7_0 is not set
# CT_CC_GCC_V_linaro_4_6 is not set
# CT_CC_GCC_V_4_6_4 is not set
# CT_CC_GCC_V_4_6_3 is not set
# CT_CC_GCC_V_4_6_2 is not set
# CT_CC_GCC_V_4_6_1 is not set
# CT_CC_GCC_V_4_6_0 is not set
# CT_CC_GCC_V_linaro_4_5 is not set
# CT_CC_GCC_V_4_5_3 is not set
# CT_CC_GCC_V_4_5_2 is not set
# CT_CC_GCC_V_4_5_1 is not set
# CT_CC_GCC_V_4_5_0 is not set
# CT_CC_GCC_V_linaro_4_4 is not set
# CT_CC_GCC_V_4_4_7 is not set
# CT_CC_GCC_V_4_4_6 is not set
# CT_CC_GCC_V_4_4_5 is not set
# CT_CC_GCC_V_4_4_4 is not set
# CT_CC_GCC_V_4_4_3 is not set
# CT_CC_GCC_V_4_4_2 is not set
# CT_CC_GCC_V_4_4_1 is not set
# CT_CC_GCC_V_4_4_0 is not set
# CT_CC_GCC_V_4_3_6 is not set
# CT_CC_GCC_V_4_3_5 is not set
# CT_CC_GCC_V_4_3_4 is not set
# CT_CC_GCC_V_4_3_3 is not set
# CT_CC_GCC_V_4_3_2 is not set
# CT_CC_GCC_V_4_3_1 is not set
# CT_CC_GCC_V_4_2_4 is not set
# CT_CC_GCC_V_4_2_2 is not set
CT_CC_GCC_4_2_or_later=y
CT_CC_GCC_4_3_or_later=y
CT_CC_GCC_4_4_or_later=y
CT_CC_GCC_4_5_or_later=y
CT_CC_GCC_4_6_or_later=y
CT_CC_GCC_4_7_or_later=y
CT_CC_GCC_4_8_or_later=y
CT_CC_GCC_4_9_or_later=y
CT_CC_GCC_5_2=y
CT_CC_GCC_5_2_or_later=y
CT_CC_GCC_5_1_or_later=y
CT_CC_GCC_HAS_GRAPHITE=y
CT_CC_GCC_USE_GRAPHITE=y
CT_CC_GCC_HAS_LTO=y
CT_CC_GCC_USE_LTO=y
CT_CC_GCC_HAS_PKGVERSION_BUGURL=y
CT_CC_GCC_HAS_BUILD_ID=y
CT_CC_GCC_HAS_LNK_HASH_STYLE=y
CT_CC_GCC_USE_GMP_MPFR=y
CT_CC_GCC_USE_MPC=y
CT_CC_GCC_HAS_LIBQUADMATH=y
CT_CC_GCC_HAS_LIBSANITIZER=y
CT_CC_GCC_VERSION="5.2.0"
# CT_CC_LANG_FORTRAN is not set
CT_CC_GCC_ENABLE_CXX_FLAGS=""
CT_CC_GCC_CORE_EXTRA_CONFIG_ARRAY=""
CT_CC_GCC_EXTRA_CONFIG_ARRAY=""
CT_CC_GCC_EXTRA_ENV_ARRAY=""
CT_CC_GCC_STATIC_LIBSTDCXX=y
# CT_CC_GCC_SYSTEM_ZLIB is not set

#
# Optimisation features
#

#
# Settings for libraries running on target
#
CT_CC_GCC_ENABLE_TARGET_OPTSPACE=y
# CT_CC_GCC_LIBMUDFLAP is not set
# CT_CC_GCC_LIBGOMP is not set
# CT_CC_GCC_LIBSSP is not set
# CT_CC_GCC_LIBQUADMATH is not set

#
# Misc. obscure options.
#
CT_CC_CXA_ATEXIT=y
# CT_CC_GCC_DISABLE_PCH is not set
CT_CC_GCC_LDBL_128=m
# CT_CC_GCC_BUILD_ID is not set
CT_CC_GCC_LNK_HASH_STYLE_DEFAULT=y
# CT_CC_GCC_LNK_HASH_STYLE_SYSV is not set
# CT_CC_GCC_LNK_HASH_STYLE_GNU is not set
# CT_CC_GCC_LNK_HASH_STYLE_BOTH is not set
CT_CC_GCC_LNK_HASH_STYLE=""
CT_CC_GCC_DEC_FLOAT_AUTO=y
# CT_CC_GCC_DEC_FLOAT_BID is not set
# CT_CC_GCC_DEC_FLOAT_DPD is not set
# CT_CC_GCC_DEC_FLOATS_NO is not set
CT_CC_SUPPORT_CXX=y
CT_CC_SUPPORT_FORTRAN=y
CT_CC_SUPPORT_JAVA=y
CT_CC_SUPPORT_ADA=y
CT_CC_SUPPORT_OBJC=y
CT_CC_SUPPORT_OBJCXX=y
CT_CC_SUPPORT_GOLANG=y

#
# Additional supported languages:
#
CT_CC_LANG_CXX=y

#
# Debug facilities
#
# CT_DEBUG_dmalloc is not set
# CT_DEBUG_duma is not set
CT_DEBUG_gdb=y
CT_GDB_CROSS=y
# CT_GDB_CROSS_STATIC is not set
# CT_GDB_CROSS_SIM is not set
CT_GDB_CROSS_PYTHON=y
CT_GDB_CROSS_EXTRA_CONFIG_ARRAY=""

#
# In bare-metal, you'll need to   
#

#
# provide your own gdbserver stub.
#

#
# gdb version
#
# CT_DEBUG_GDB_SHOW_LINARO is not set
CT_GDB_V_7_10=y
# CT_GDB_V_7_9_1 is not set
# CT_GDB_V_7_9 is not set
# CT_GDB_V_7_8_2 is not set
# CT_GDB_V_7_8_1 is not set
# CT_GDB_V_7_8 is not set
# CT_GDB_V_7_7_1 is not set
# CT_GDB_V_7_7 is not set
# CT_GDB_V_7_6_1 is not set
# CT_GDB_V_7_5_1 is not set
# CT_GDB_V_7_4_1 is not set
# CT_GDB_V_7_4 is not set
# CT_GDB_V_7_3_1 is not set
# CT_GDB_V_7_3a is not set
# CT_GDB_V_7_2a is not set
# CT_GDB_V_7_1a is not set
# CT_GDB_V_7_0_1a is not set
# CT_GDB_V_7_0a is not set
# CT_GDB_V_6_8a is not set
CT_GDB_7_2_or_later=y
CT_GDB_7_0_or_later=y
CT_GDB_HAS_PKGVERSION_BUGURL=y
CT_GDB_HAS_PYTHON=y
CT_GDB_INSTALL_GDBINIT=y
CT_GDB_VERSION="7.10"
# CT_DEBUG_ltrace is not set
CT_DEBUG_strace=y
CT_STRACE_V_4_10=y
# CT_STRACE_V_4_9 is not set
# CT_STRACE_V_4_8 is not set
# CT_STRACE_V_4_7 is not set
# CT_STRACE_V_4_6 is not set
# CT_STRACE_V_4_5_20 is not set
# CT_STRACE_V_4_5_19 is not set
# CT_STRACE_V_4_5_18 is not set
CT_STRACE_VERSION="4.10"

#
# Companion libraries
#
CT_COMPLIBS_NEEDED=y
CT_GMP_NEEDED=y
CT_MPFR_NEEDED=y
CT_ISL_NEEDED=y
CT_MPC_NEEDED=y
CT_COMPLIBS=y
CT_GMP=y
CT_MPFR=y
CT_ISL=y
CT_MPC=y
CT_GMP_V_6_0_0=y
# CT_GMP_V_5_1_3 is not set
# CT_GMP_V_5_1_1 is not set
# CT_GMP_V_5_0_2 is not set
# CT_GMP_V_5_0_1 is not set
# CT_GMP_V_4_3_2 is not set
# CT_GMP_V_4_3_1 is not set
# CT_GMP_V_4_3_0 is not set
CT_GMP_5_0_2_or_later=y
CT_GMP_VERSION="6.0.0a"
CT_MPFR_V_3_1_3=y
# CT_MPFR_V_3_1_2 is not set
# CT_MPFR_V_3_1_0 is not set
# CT_MPFR_V_3_0_1 is not set
# CT_MPFR_V_3_0_0 is not set
# CT_MPFR_V_2_4_2 is not set
# CT_MPFR_V_2_4_1 is not set
# CT_MPFR_V_2_4_0 is not set
CT_MPFR_VERSION="3.1.3"
CT_ISL_V_0_14=y
# CT_ISL_V_0_12_2 is not set
CT_ISL_V_0_14_or_later=y
CT_ISL_V_0_12_or_later=y
CT_ISL_VERSION="0.14"
CT_MPC_V_1_0_3=y
# CT_MPC_V_1_0_2 is not set
# CT_MPC_V_1_0_1 is not set
# CT_MPC_V_1_0 is not set
# CT_MPC_V_0_9 is not set
# CT_MPC_V_0_8_2 is not set
# CT_MPC_V_0_8_1 is not set
# CT_MPC_V_0_7 is not set
CT_MPC_VERSION="1.0.3"

#
# Companion libraries common options
#
# CT_COMPLIBS_CHECK is not set

#
# Companion tools
#

#
# READ HELP before you say 'Y' below !!!
#
# CT_COMP_TOOLS is not set
```

**Comment by gosfon** [comment] 2015-10-13 06:34
I found a similar experience in [Here](https://sourceware.org/ml/crossgcc/2015-02/msg00029.html).
it fixed the problem by changed the Linaro binutils and linaro newlib to the straight binutils and newlib, but I had already use the straight binutils and newlib and stll failed.

**Comment by bhundven** [comment] 2015-10-14 00:29
I've never used OpenSuse, so it will take me a bit to get a vm up to test.

**Comment by gosfon** [comment] 2015-10-17 09:47
I try it in ubuntu 10.04.4 with the same congifuration, but got the same error. Were there  something wrongs with my congifuration or something else?

**Comment by bhundven** [comment] 2015-10-19 22:19
I believe it is an environment issue. A package is missing. I'm still working to reproduce the issue on OpenSuse.

**Comment by bhundven** [comment] 2015-11-13 10:45
@gosfon Looking into this a little bit more, it seems to not be an issue with crosstool-ng.
I have updated the title of the bug, as such.

Take a look at:
https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=libgloss/arm/configure.in;h=39c15d724bc4c9cbc6c1bb4cc1f86cbcbf0e6a07;hb=HEAD#l51

Newlib, from the latest git repository, does not support ```*-*-eabihf```, and this is causing the issue.
By not matching there, ```elf-``` does not get suffixed to the spec name, and since newlib does not support linux targets that are not elf, the build fails.

I'm closing this issue as you need to get this fixed in newlib.
They should change the match to ```*-*-eabi*```, and verify they support hard-float.

**Closed by bhundven** 2015-11-13 10:45 UTC
Labels: confirmed, wontfix
