### ISSUE TITLE
Error while building gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]

### ISSUE THREAD

**Issue by archcomp** [crosstool-ng/crosstool-ng#992] opened 2018-06-18 12:42 UTC
Using crosstool-NG 1.23.0  with Ubuntu 18.04 LTS. 
When Building, it gives error 
 =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    /home/mv/crosstool-ng/.build/src/gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
[ERROR]    make[2]: *** [ubsan.o] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [all-gcc] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@674]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@227]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
Build Log file attached.
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2111244/build.log)

**Comment by gmac80** [comment] 2018-07-02 15:41
Hi, 
When compiling using pages 3 and 5 of [Bootlin's instructions](https://bootlin.com/doc/training/embedded-linux/embedded-linux-labs.pdf) on Ubuntu 18.04 LTS, I had the same issue, but was able to compile once I inserted a cast:
``  if (xloc.file == NULL || strncmp (xloc.file, "\1", 2) == 0
      || xloc.file == **(const char*)**'\0' || xloc.file[0] == '\xff'
      || xloc.file[1] == '\xff')

**Comment by tpetazzoni** [comment] 2018-07-03 11:42
This issue is a duplicate of https://github.com/crosstool-ng/crosstool-ng/issues/735, i.e the problem exists in CT-NG 1.23.0 but not in later versions.

**Comment by halilgithub** [comment] 2018-07-16 21:58
@gmac80 

In which file did you do the fix ?

**Comment by stilor** [comment] 2018-09-28 20:35
The fix was in one of the patches in the `packages/gcc`; AFAIR it is fixed in the current GCC6 release upstream (6.4).

**Closed by stilor** 2018-09-28 20:35 UTC

**Comment by stilor** [comment] 2018-09-28 20:37
@gmac80 No, your fix was not correct: your check is equivalent to the 1st condition (`xloc.file == NULL`). It should've been `xloc.file[0] == '\0'`.

**Comment by gmac80** [comment] 2018-09-28 20:56
Ok, but that was the source of the error in the first place - "ISO C++
forbids comparison between pointer and integer [-fpermissive]". What's the
'correct' way of comparing the pointer and the integer / character in this
case?

**Comment by gmac80** [comment] 2018-09-28 20:58
Thomas, sorry I completely forgot to answer you. The same file as in the
compiler messages at the top of the post: src/gcc-6.3.0/gcc/ubsan.c
