### ISSUE TITLE
error: cannot determine stat(1) format option

### ISSUE THREAD

**Issue by ju8crafter-jaXnein** [crosstool-ng/crosstool-ng#1075] opened 2018-10-29 11:40 UTC
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/2525052/config.log)
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

Please help me!
![grafik](https://user-images.githubusercontent.com/16226664/47647496-78424400-db77-11e8-9cd4-1d62690bd2ad.png)

**Comment by stilor** [comment] 2018-10-30 04:19
No host OS specified. Besides, a duplicate of #890.

**Closed by stilor** 2018-10-30 04:19 UTC

**Comment by stilor** [comment] 2018-10-30 04:30
Sorry, not #890 but one of #749 or #836. If `touch /tmp/foo && chmod 642 /tmp/foo && stat -c '%a' /tmp/foo` reports `642`, check if `which stat` refers to any wrapper (e.g. "colorizing wrapper" on archlinux).

**Comment by ju8crafter-jaXnein** [comment] 2018-11-02 11:32
`which stat` returns /usr/bin/stat

**Comment by ju8crafter-jaXnein** [comment] 2018-11-02 18:00
`which stat` returns /usr/bin/stat

**Comment by ju8crafter-jaXnein** [comment] 2018-11-02 18:01
so how can i fix it now?

**Comment by stilor** [comment] 2018-11-03 04:47
`touch /tmp/foo && chmod 642 /tmp/foo && stat -c '%a' /tmp/foo`
?

**Comment by stilor** [comment] 2018-11-03 04:47
and please look at the issue submission guidelines and fill in the missing bits

**Comment by ju8crafter-jaXnein** [comment] 2018-11-06 18:05
`touch /tmp/foo && chmod 642 /tmp/foo && stat -c '%a' /tmp/foo` returns: 642
`uname -a` returns:
Linux DESKTOP-C25F5J6 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018 x86_64 GNU/Linux
crosstool ver: crosstool-ng-1.23.0

**Comment by stilor** [comment] 2018-11-06 19:36
Is it WSL? It is not officially supported (yet). Either you can debug `configure` - why the same test yields something different; or you need to wait until I have the time to install WSL on my windows machine.

**Comment by ju8crafter-jaXnein** [comment] 2018-11-14 16:03
Could you message me when WSl is supported?

**Comment by stilor** [comment] 2018-11-14 16:59
I did install it yesterday, actually, on my machine. I tried Ubuntu first; it configured and installed ct-ng successfully. I haven't tried to build any samples yet, will try it tonight - but it correctly determined stat format as GNU.

Which version (Ubuntu/Kali/...) did you install?

What is the language setting in the shell (`echo $LANGUAGE; echo $LANG; echo $LC_ALL; echo $LC_MESSAGES`)? If it is non-English, can you try `export LANGUAGE=en_US; export LANG=en_US.UTF8; unset LC_ALL; unset LC_MESSAGES` and retry?

**Comment by ju8crafter-jaXnein** [comment] 2018-11-14 17:32
![grafik](https://user-images.githubusercontent.com/16226664/48500626-9e383b80-e83b-11e8-934c-0eff1d98c13a.png)

**Comment by stilor** [comment] 2018-11-14 17:36
Which version did you install, Ubuntu or anything else?

If it is Ubuntu (same as mine), then I am officially out of ideas. Sorry. It worked for me and I don't have the time to debug it on your machine. You might need to dig into the configure (it is just a shell script, after all) and find why the test which passes on the command line (touch-chmod-stat) fails in the script.

**Comment by ju8crafter-jaXnein** [comment] 2018-11-14 17:38
its Debian

**Comment by chrisjbreisch** [comment] 2018-11-14 21:02
I just installed Debian WSL, and ran the following. It worked.

`
$ sudo apt update
$ sudo apt install build-essential
$ sudo apt install gawk bison texinfo autoconf automake
$ sudo apt install unzip help2man
$ mkdir ctng
$ cd ctng
$ sudo apt install git
$ git clone https://github.com/crosstool-ng/crosstool-ng
$ cd crosstool-ng/
$ ./bootstrap
$ sudo apt install flex
$ sudo apt install file
$ sudo apt install libtool
$ sudo apt install man
$ sudo apt install libtool-bin
$ sudo apt install libncurses5 libncurses5-dev
$ ./configure --prefix=/home/chris/ctng
`

**Comment by ju8crafter-jaXnein** [comment] 2018-11-15 16:09
that doesnt work for me chris still the same error and while running `./bootstrap` this came up:
configure.ac:246: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:247: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
could this be the problem?

**Comment by stilor** [comment] 2018-11-15 20:18
No, these warnings should be harmless. When generating configure from configure.ac, autoconf first reads the system library of its m4 "modules", then tries to parse the configure.ac and while doing so, discovers more module include directories. We provide a gettext.m4 module in crosstool-NG (inside the m4/ directory) and you don't have it installed system-wide. If the warning bothers you, you can install gettext package and it should go away.

I suggest you open the configure script in some text editor, find the location where it tests for stat option format and try to find what is going wrong.

**Comment by stilor** [comment] 2018-11-17 22:12
Line number would be pointless, as this file is auto-generated: line number would change with even unrelated commits, or can differ if you have a different version of autoconf on the host.

Instead, just search for the message it prints around this check, `whether stat takes`.

**Comment by ju8crafter-jaXnein** [comment] 2018-11-18 15:19
is it possible that autoconf makes a file with programming errors?

**Comment by ljelen** [comment] 2019-03-19 01:31
This faliure shows up when you try build crosstol-ng on pratition with filesystems e.g. ntfs
