### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by deep5050** [crosstool-ng/crosstool-ng#2065] opened 2023-11-08 09:38 UTC
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

====  Building crosstool-ng-1.24.0 ====
```
make: Entering directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0'
/usr/bin/make  all-recursive
make: Entering directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0'
Making all in kconfig
make: Entering directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0/kconfig'
flex -L -Pzconf  -ozconf.lex.c zconf.l
/usr/bin/make  all-am
make: Entering directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0/kconfig'
depbase=`echo conf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT conf.o -MD -MP -MF $depbase.Tpo -c -o conf.o conf.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo zconf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT zconf.o -MD -MP -MF $depbase.Tpo -c -o zconf.o zconf.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"  -D_GNU_SOURCE  -g -O2 -MT nconf-nconf.o -MD -MP -MF .deps/nconf-nconf.Tpo -c -o nconf-nconf.o `test -f 'nconf.c' || echo './'`nconf.c
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"  -D_GNU_SOURCE  -g -O2 -MT nconf-nconf.gui.o -MD -MP -MF .deps/nconf-nconf.gui.Tpo -c -o nconf-nconf.gui.o `test -f 'nconf.gui.c' || echo './'`nconf.gui.c
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"  -D_GNU_SOURCE  -g -O2 -MT nconf-zconf.o -MD -MP -MF .deps/nconf-zconf.Tpo -c -o nconf-zconf.o `test -f 'zconf.c' || echo './'`zconf.c
mv -f .deps/nconf-nconf.gui.Tpo .deps/nconf-nconf.gui.Po
depbase=`echo mconf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT mconf.o -MD -MP -MF $depbase.Tpo -c -o mconf.o mconf.c &&\
mv -f $depbase.Tpo $depbase.Po
mv -f .deps/nconf-nconf.Tpo .deps/nconf-nconf.Po
depbase=`echo lxdialog/checklist.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/checklist.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/checklist.o lxdialog/checklist.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lxdialog/inputbox.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/inputbox.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/inputbox.o lxdialog/inputbox.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lxdialog/menubox.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/menubox.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/menubox.o lxdialog/menubox.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lxdialog/textbox.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/textbox.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/textbox.o lxdialog/textbox.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lxdialog/util.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/util.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/util.o lxdialog/util.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo lxdialog/yesno.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/yesno.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/yesno.o lxdialog/yesno.c &&\
mv -f $depbase.Tpo $depbase.Po
/usr/bin/libtool  --tag CC  --mode=link gcc  -g -O2   -o conf conf.o zconf.o
/usr/bin/libtool  --tag CC  --mode=link gcc  -g -O2   -o mconf mconf.o zconf.o lxdialog/checklist.o lxdialog/inputbox.o lxdialog/menubox.o lxdialog/textbox.o lxdialog/util.o lxdialog/yesno.o -lncurses
libtool: link: gcc -g -O2 -o conf conf.o zconf.o
libtool: link: gcc -g -O2 -o mconf mconf.o zconf.o lxdialog/checklist.o lxdialog/inputbox.o lxdialog/menubox.o lxdialog/textbox.o lxdialog/util.o lxdialog/yesno.o  -lncurses
mv -f .deps/nconf-zconf.Tpo .deps/nconf-zconf.Po
/usr/bin/libtool  --tag CC  --mode=link gcc -D_GNU_SOURCE  -g -O2   -o nconf nconf-nconf.o nconf-nconf.gui.o nconf-zconf.o -lmenu -lpanel -lncurses
libtool: link: gcc -D_GNU_SOURCE -g -O2 -o nconf nconf-nconf.o nconf-nconf.gui.o nconf-zconf.o  -lmenu -lpanel -lncurses
make: Leaving directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0/kconfig'
make: Leaving directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0/kconfig'
make: Entering directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0'
( /bin/sed -e 's,[@]docdir[@],/usr/local/share/doc/crosstool-ng,g' -e 's,[@]pkgdatadir[@],/usr/local/share/crosstool-ng,g' -e 's,[@]pkglibexecdir[@],/usr/local/libexec/crosstool-ng,g' -e 's,[@]progname[@],'`echo ct-ng | sed 's,x,x,'`',g' | /bin/bash config.status --file=- ) < ct-ng.in >ct-ng-t && chmod a-w,a+x ct-ng-t && mv -f ct-ng-t ct-ng
/bin/mkdir -p bash-completion && ( /bin/sed -e 's,[@]docdir[@],/usr/local/share/doc/crosstool-ng,g' -e 's,[@]pkgdatadir[@],/usr/local/share/crosstool-ng,g' -e 's,[@]pkglibexecdir[@],/usr/local/libexec/crosstool-ng,g' -e 's,[@]progname[@],'`echo ct-ng | sed 's,x,x,'`',g' | /bin/bash config.status --file=- ) < bash-completion/ct-ng.in >bash-completion/ct-ng-t && mv -f bash-completion/ct-ng-t bash-completion/ct-ng
/bin/mkdir -p docs && ( /bin/sed -e 's,[@]docdir[@],/usr/local/share/doc/crosstool-ng,g' -e 's,[@]pkgdatadir[@],/usr/local/share/crosstool-ng,g' -e 's,[@]pkglibexecdir[@],/usr/local/libexec/crosstool-ng,g' -e 's,[@]progname[@],'`echo ct-ng | sed 's,x,x,'`',g' | /bin/bash config.status --file=- ) < docs/ct-ng.1.in >docs/ct-ng.1-t && mv -f docs/ct-ng.1-t docs/ct-ng.1
make: Leaving directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0'
make: Leaving directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0'
make: Leaving directory '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0'
====  Building xtools for armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38 in /home/tatha/onie/build/x-tools/armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38/build ====
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/tatha/onie/build/x-tools/armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38/build'
[INFO ]  Performing some trivial sanity checks
[WARN ]  Number of open files 1024 may not be sufficient to build the toolchain; increasing to 2048
[INFO ]  Build started 20231108.093458
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[ERROR]    Internal ct-ng error: 'LINUX' not defined, please report a bug
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2051]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2174]
[ERROR]  >>        called from: do_kernel_get[scripts/build/kernel/linux.sh@22]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@647]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0/docs/manual/B_Known_issues.md'
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >> NOTE: You configuration uses non-default patch sets. Please
[ERROR]  >> select 'bundled' as the set of patches applied and attempt
[ERROR]  >> to reproduce this issue. Issues reported with other patch
[ERROR]  >> set selections (none, local, bundled+local) are going to be
[ERROR]  >> closed without explanation.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 0:01.06)
/home/tatha/onie/build/crosstool-ng/crosstool-ng-1.24.0/ct-ng:261: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/tatha/onie/build/x-tools/armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38/build'
rm: cannot remove '/home/tatha/onie/build/x-tools/armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38/build/.config.2': No such file or directory
make/xtools.make:144: recipe for target '/home/tatha/onie/build/x-tools/armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38/stamp/xtools-build' failed
make: *** [/home/tatha/onie/build/x-tools/armv7a-g8.3.0-lnx4.1.38-uClibc-ng-1.0.38/stamp/xtools-build] Error 1
tatha@due-onie-build-debian-9:~/onie/build-config$
```

**Comment by QBos07** [comment] 2023-11-08 18:05
You are not using default patches! change that or explain why.

**Comment by cpackham** [comment] 2023-11-09 20:23
"bug" doesn't help describing your issue. You also haven't attached `build.log` or `.config` so it's hard for anyone to tell what's going on if you manage to convince them to open the issue.

From what you have supplied it looks like you're using onie and it looks like they are using an old version of crosstool-ng https://github.com/opencomputeproject/onie/blob/master/build-config/make/crosstool-ng.make. You'd be better off reporting the issue over there https://github.com/opencomputeproject/onie/issues and maybe suggesting they update to a newer crosstool-ng version.

**Comment by cpackham** [comment] 2023-11-13 22:34
I raised https://github.com/opencomputeproject/onie/pull/1047 with ONIE. That'll at least direct people to them but maybe it'll prompt them to update.

Closing this issue as it doesn't provide any of the basic info or even attempt to reproduce on master (or even the latest released version).

**Closed by cpackham** 2023-11-13 22:34 UTC
