### ISSUE TITLE
zlib: download failed

### ISSUE THREAD

**Issue by dia2e2** [crosstool-ng/crosstool-ng#1836] opened 2022-10-16 02:42 UTC
I am trying to crosstool-NG toolchain and I keep running into this error message. 

INFO ]  Performing some trivial sanity checks
[WARN ]  Number of open files 1024 may not be sufficient to build the toolchain; increasing to 2048
[INFO ]  Build started 20221015.223452
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = arm-cortex_a8-linux-gnueabihf
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.22s (at 00:06)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'zlib-1.2.12'
[ERROR]    zlib: download failed
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2129]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2089]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2200]
[ERROR]  >>        called from: do_zlib_get[scripts/build/companion_libs/050-zlib.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@649]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 0:06.65)
[00:09] / gmake: *** [ct-ng:261: build] Error 1

**Comment by cpackham** [comment] 2022-10-16 02:58
duplicate of #1832

Short answer is download it manually from https://www.zlib.net/fossils/zlib-1.2.12.tar.gz

**Comment by dia2e2** [comment] 2022-10-16 03:26
Did the installation manually but it's still giving me the same error message

alex@alex:~/crosstool-ng$ wget https://www.zlib.net/fossils/zlib-1.2.12.tar.gz
--2022-10-15 23:16:44--  https://www.zlib.net/fossils/zlib-1.2.12.tar.gz
Resolving [www.zlib.net](http://www.zlib.net/) ([www.zlib.net](http://www.zlib.net/))... 85.187.148.2
Connecting to [www.zlib.net](http://www.zlib.net/) ([www.zlib.net](http://www.zlib.net/))|85.187.148.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1490071 (1.4M) [application/x-gzip]
Saving to: ‘zlib-1.2.12.tar.gz’

zlib-1.2.12.tar.gz        100%[=====================================>]   1.42M  2.65MB/s    in 0.5s    

2022-10-15 23:16:45 (2.65 MB/s) - ‘zlib-1.2.12.tar.gz’ saved [1490071/1490071]

alex@alex:~/crosstool-ng$ ./ct-ng build
[INFO ]  Performing some trivial sanity checks
[WARN ]  Number of open files 1024 may not be sufficient to build the toolchain; increasing to 2048
[INFO ]  Build started 20221015.231704
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = arm-cortex_a8-linux-gnueabihf
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.19s (at 00:09)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'zlib-1.2.12'
[ERROR]    zlib: download failed
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2129]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2089]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2200]
[ERROR]  >>        called from: do_zlib_get[scripts/build/companion_libs/050-zlib.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@649]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 0:07.90)
[00:11] / gmake: *** [ct-ng:261: build] Error 1

**Comment by cpackham** [comment] 2022-10-16 06:49
You need to make sure the tarball is in the correct location (by default
this is ~/src).

**Closed** 2022-10-18 04:29 UTC
