### ISSUE TITLE
maybe option to modify -dumpmachine value?

### ISSUE THREAD

**Issue by tofutim** [crosstool-ng/crosstool-ng#926] opened 2018-03-01 10:51 UTC
I have been trying to cross compile QT for Raspberry Pi (Raspbian Stretch) on OSX 10.13 using crosstool-ng-1.23.0-319-gaca85cbb. Raspbian Stretch puts many of its core libraries in directories like `/usr/lib/arm-linux-gnueabihf`. QT uses '...g++ -dumpmachine' to determine the tuple, and this ended up for me being `/usr/lib/arm-raspbian-linux-gnueabihf` despite having a CT_TARGET_ALIAS of arm-linux-gnueabihf.

The tools from Raspberry Pi end up setting the CT_TARGET directly
```
#
# Tuple completion and aliasing
#
CT_TARGET_VENDOR="rpi"
CT_TARGET_ALIAS_SED_EXPR=""
CT_TARGET_ALIAS=""
CT_TARGET=arm-linux-gnueabihf
```

but this is not an option from menuconfig and probably ill-advised anyway. Instead, I wonder if it would be possible to set the -dumpmachine value. (Hmm, on second thought maybe that is not a good idea either. ) I was tempted to change the Build system Tuple. Could that be it? Or is that something else?

![image](https://user-images.githubusercontent.com/157766/36840829-402e4ad6-1cfb-11e8-8ba8-cf00b3d3e235.png)

I was thinking the Build system Tuple is actually my mac and has nothing to do with the output gcc, but the Help is not so clear

![image](https://user-images.githubusercontent.com/157766/36840858-5b29863e-1cfb-11e8-97f8-3be74e31c627.png)

and I really don't know what I'm doing.
In case anyone else runs into this, I ended up modifying configuration code in QT:
```
--- a/configure.pri
+++ b/configure.pri
@@ -241,7 +241,7 @@ defineReplace(qtConfFunc_licenseCheck) {
 
 # this is meant for linux device specs only
 defineTest(qtConfTest_machineTuple) {
-    qtRunLoggedCommand("$$QMAKE_CXX -dumpmachine", $${1}.tuple)|return(false)
+    qtRunLoggedCommand("$$QMAKE_CXX -dumpmachine | sed 's/-raspbian//'", $${1}.tuple)|return(false)
     $${1}.cache += tuple
     export($${1}.cache)
     return(true)
```

**Comment by stilor** [comment] 2018-04-11 06:44
You're right about the build tuple: this is indeed your mac (assuming you run crosstool-NG on mac).

Regarding the target tuple, the recommended naming is CPU-VENDOR-OS or CPU-VENDOR-OS-LIBC. Yours is a three-component form (arm-linux-gnueabihf), but it is CPU-OS-LIBC with missing VENDOR part. Off-hand I do not remember the library search path on arm-*-linux, but it is not necessarily tied to the target tuple.

**Comment by stilor** [comment] 2018-12-01 21:10
The request for an ability to remove the VENDOR part of the target tuple seems to be a duplicate of #1019; I'll consider merging that one due to popular demand (after fixing it as I suggested in the review - the OP seems to have gone away).

**Closed by stilor** 2018-12-01 21:10 UTC
