### ISSUE TITLE
Build failed in step 'Installing m4 for build'

### ISSUE THREAD

**Issue by asalfo** [crosstool-ng/crosstool-ng#1097] opened 2018-11-20 19:42 UTC
I got this error when building:
/usr/local/Cellar/crosstool-ng/1.23.0_2/lib/crosstool-ng-1.23.0/scripts/functions: line 297: 69886 Segmentation fault: 11  "${@}" 2>&1

Crosstool-NG version crosstool-ng-1.23.0
macOS version 10.14.1  (Mojave)
Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2601287/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/2601303/config.txt)

Thanks

**Comment by stevielavern** [comment] 2018-11-22 08:05
Exact same issue here.

**Comment by stilor** [comment] 2018-11-24 05:53
All I can say from the build.log is that apparently, the `make` utility that crosstool-NG built right before the m4 crashed for some reason. You can try to use the hst make, if one is installed. You can also try crosstool-NG from master to see if it has been fixed. If that doesn't work - sorry, I don't have a macOS system to debug the issues like this, and Apple hasn't been very friendly to let people run their OS in virtual machines.

As I mentioned elsewhere, macOS is now officially unsupported. I'll review/pick up the patch if one posts a PR for this issue but won't attempt to guess the root cause myself. Closing this issue.

**Closed** 2018-11-24 06:02 UTC

**Comment by brandon-powell** [comment] 2018-12-31 09:14
This appears to be caused by invalid binutils binaries. I had the same issue but was able to isolate it to the binutils package installed through homebrew. The fix is to uninstall and reinstall binutils via brew (you may have to use the --ignore-dependencies flag) or recompile binutils if you built them from source. 

I can't test this now since I've already reinstalled my binutils, but my best guess is that Homebrew didn't automatically update the binutils to the Mojave bottle we upgraded from High Sierra to Mojave (because there haven't been any actual binutils version changes since then), and there was an ABI difference that affected binutils.

**Comment by scr34m** [comment] 2019-02-01 16:42
I can confirm this. 

These two commands fix the issue reported by @asalfo 
```
brew uninstall --ignore-dependencies binutils
brew install binutils
```

**Comment by axos88** [comment] 2019-03-13 21:14
I can confirm this, it @scr34m's suggestion fixed it for me too. I recently upgraded to mojave, might've been the reason why my binutils broke.

**Comment by a0s** [comment] 2022-01-31 16:50
No, it doesn't help
```
> ./ct-ng build                                
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20220131.193755
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-apple-darwin19.6.0
[EXTRA]      host   = x86_64-apple-darwin19.6.0
[EXTRA]      target = xtensa-esp32-elf
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.00s (at 00:16)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 4.00s (at 00:20)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting binutils-git-2802c5b8
[EXTRA]    Patching binutils-git-2802c5b8
[EXTRA]    Extracting gcc-git-f9333cfc
[EXTRA]    Patching gcc-git-f9333cfc
[EXTRA]    Extracting newlib-git-af7e0ec3
[EXTRA]    Patching newlib-git-af7e0ec3
[EXTRA]    Extracting gdb-git-9a47478f
[EXTRA]    Patching gdb-git-9a47478f
[INFO ]  Extracting and patching toolchain components: done in 114.00s (at 02:14)
[INFO ]  =================================================================
[INFO ]  Installing m4 for build
[EXTRA]    Configuring m4
[EXTRA]    Building m4
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[3]: *** [Makefile:1555: m4] Error 1
[ERROR]    make[2]: *** [Makefile:1572: all-recursive] Error 1
[ERROR]    make[1]: *** [Makefile:1528: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing m4 for build'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_m4_backend[scripts/build/companion_tools/100-m4.sh@69]
[ERROR]  >>        called from: do_companion_tools_m4_for_build[scripts/build/companion_tools/100-m4.sh@18]
[ERROR]  >>        called from: do_companion_tools_for_build[scripts/build/companion_tools.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 4:00.00)
[04:01] / gmake: *** [ct-ng:261: build] Error 2
```

i am at (HEAD -> esp-1.24.x, origin/esp-1.24.x, origin/HEAD) of https://github.com/espressif/crosstool-NG but the problem is common for repos

**Comment by isinyaaa** [comment] 2022-04-29 22:21
@a0s have you added the binutils stuff to your environment? e.g. for me (using fish) homebrew says

<img width="668" alt="image" src="https://user-images.githubusercontent.com/39812919/166076105-9c90a208-e725-440d-aa65-c06b7527deba.png">
