### ISSUE TITLE
Canadian x86_64-apple-darwin15 undefined symbols`_fread_unlocked`

### ISSUE THREAD

**Issue by mobileoverlord** [crosstool-ng/crosstool-ng#851] opened 2017-10-25 02:00 UTC
Crosstool-NG v1.28.0
build  = x86_64-pc-linux-gnu
host   = x86_64-apple-darwin15
target = armv6-rpi-linux-gnueabi

Uploaded compressed `build.log` and `.config`
[build.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1413021/build.tar.gz)

I am using a cross compiler toolchain that runs on `x86_64-linux-gnu` and compiles for `x86_64-apple-darwin15`. This toolchain is a product of [osxcross](https://github.com/tpoechtrager/osxcross)

The build gets to the step `Installing final gcc compiler` and fails when trying to link library symbols for `_fread_unlocked`.

```
[ALL  ]    x86_64-host_apple-darwin15-g++    -O2 -g -pipe -I/home/jschneck/dev/nerves/toolchains/work-darwin-x86_64-nerves_toolchain_armv6_rpi_linux_gnueabi/build/.build/HOST-x86_64-apple-darwin15/armv6-rpi-linux-gnueabi/buildtools/complibs-host/include  -fno-common -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc -Wl,-no_pie -L/home/jschneck/dev/nerves/toolchains/work-darwin-x86_64-nerves_toolchain_armv6_rpi_linux_gnueabi/build/.build/HOST-x86_64-apple-darwin15/armv6-rpi-linux-gnueabi/buildtools/complibs-host/lib  -framework CoreFoundation -lstdc++ -lm -o xgcc gcc.o gcc-main.o ggc-none.o spellcheck.o   c/gccspec.o  libcommon-target.a    libcommon.a ../libcpp/libcpp.a  /home/jschneck/dev/nerves/toolchains/work-darwin-x86_64-nerves_toolchain_armv6_rpi_linux_gnueabi/build/.build/HOST-x86_64-apple-darwin15/armv6-rpi-linux-gnueabi/buildtools/complibs-host/lib/libiconv.a ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a
[ALL  ]    Undefined symbols for architecture x86_64:
[ALL  ]      "_fread_unlocked", referenced from:
[ALL  ]          yylex(char const**) in gengtype-lex.o
[ALL  ]    ld: symbol(s) not found for architecture x86_64
[ERROR]    collect2: error: ld returned 1 exit status
```

**Comment by stilor** [comment] 2017-10-26 04:39
First, since you obviously have a time machine, can you please upload release 1.28 somewhere? :) it would save me a lot of work if I could get the code five releases ahead :)

Seriously though, I am not familiar with osxcross, but it looks like a problem with that toolchain: gengtype-lex.c only refers to `fread`, so the substitution with `_fread_unlocked` is performed by some headers used by osxcross toolchain - and then the libraries provided by that toolchain don't seem to provide this symbol.

**Comment by mobileoverlord** [comment] 2017-10-26 13:54
Hahaha. I definitely turned that 3 into an 8 in my head and am using 1.23.0 not 1.28.0. At least that is what the galactic federation told me to tell you since I am not allowed to really talk about my time machine. :)

I was under the impression that _fread_unlocked was a GNU thing and that it wasn't a Mac-ism. I really appreciate looking into this, I understand that this one of those "in between projects" problems so :heart: thanks in advance.

@tpoechtrager is from the osxcross project and may be able to provide more information.

**Comment by stilor** [comment] 2017-10-26 15:33
If what you write about `_fread_unlocked` is true, then the question becomes why did osxcross pick up the build machine's headers when compiling for the host (in ct-ng terms; from osxcross point of view that would be "host machine's headers when compiling for the target").

**Comment by stilor** [comment] 2017-11-08 06:25
Any news? I cannot debug osxcross toolchain, so unless there is some definite evidence pointing at ct-ng, I'm going to close the issue.

**Comment by tpoechtrager** [comment] 2017-11-08 22:01
OSXCross does include the build machine's headers. They are most likely pulled in by a configure script. I even added a warning to OSXCross to avoid these issues.

    $ x86_64-apple-darwin16-g++ -I /usr/include
    osxcross: warning: possibly dangerous include path specified: '-I /usr/include'
    osxcross: info: you can silence this warning via 'OSXCROSS_NO_INCLUDE_PATH_WARNINGS=1' (env)

This particular issue is probably caused by ` -I/home/jschneck/dev/nerves/toolchains/work-darwin-x86_64-nerves_toolchain_armv6_rpi_linux_gnueabi/build/.build/HOST-x86_64-apple-darwin15/armv6-rpi-linux-gnueabi/buildtools/complibs-host/include`

**Comment by stilor** [comment] 2017-11-11 05:47
`complibs-host` are *host*, not *build* machine's headers, so these should be fine. Besides, we don't build glibc for *host* :) I don't have an apple machine so I cannot download the SDK (to build a osxcross myself).

It also looks that configure did its job:
````
[ALL  ]    In file included from ./config.h:6:0,
[ALL  ]                     from /d/gcc-6.3.0/gcc-6.3.0/gcc/gengtype-lex.l:25:
[ALL  ]    ./auto-host.h:811:0: warning: "HAVE_DECL_FGETC_UNLOCKED" redefined
[ALL  ]     #define HAVE_DECL_FGETC_UNLOCKED 0
[ALL  ]
[ALL  ]    In file included from ./bconfig.h:3:0,
[ALL  ]                     from /home/jschneck/dev/nerves/toolchains/work-darwin-x86_64-nerves_toolchain_armv6_rpi_linux_gnueabi/build/.build/src/gcc-6.3.0/gcc/gengtype-lex.c:1:
[ALL  ]    ./auto-build.h:811:0: note: this is the location of the previous definition
[ALL  ]     #define HAVE_DECL_FGETC_UNLOCKED 1
````
(see that auto-host.h defines HAVE_DECL_FGETC_UNLOCKED as 0 and auto-build.h has it as 1). Same goes for other `*_unlocked` functions.

So @mobileoverlord if you want to pinpoint the culprit, I'd suggest you enable "Paths and misc options" -> "Debug Crosstool-NG" -> "Interactive shell on failed commands", run the build until it fails. After that, re-run the command that compiled gengtype-lex.o (it is not the last, failing command!) and:
- Add a `-H` option and see if any of the include files in /usr/include get picked up
- Replace `-c` with `-E -dD` and `-o gengtype-lex.o` with `-o tmp.c`, then open `tmp.c` and try to find out where the `_fread_unlocked` came from. You can attach `tmp.c` here, I'll have a look at it.

**Comment by stilor** [comment] 2018-02-15 17:19
Closing for inactivity.

**Closed by stilor** 2018-02-15 17:19 UTC
