### ISSUE TITLE
"list-samples" produces confused output.

### ISSUE THREAD

**Issue by carlo-bramini** [crosstool-ng/crosstool-ng#1572] opened 2021-08-10 08:09 UTC
Hello, if you try to run `ct-ng` with the `list-samples` option, you will get something like this:

```
Status  Sample name
config/versions/uClibc.in:1163:warning: choice value used outside its choice group
config/versions/uClibc.in:1168:warning: choice value used outside its choice group
config/versions/uClibc.in:1174:warning: choice value used outside its choice group
config/versions/uClibc.in:1191:warning: choice value used outside its choice group
config/versions/uClibc.in:1194:warning: choice value used outside its choice group
config/versions/uClibc.in:1197:warning: choice value used outside its choice group
config/versions/uClibc.in:1200:warning: choice value used outside its choice group
config/versions/uClibc.in:1273:warning: choice value used outside its choice group
config/versions/uClibc.in:1276:warning: choice value used outside its choice group
config/versions/uClibc.in:1279:warning: choice value used outside its choice group
config/versions/uClibc.in:1283:warning: choice value used outside its choice group
config/versions/uClibc.in:1287:warning: choice value used outside its choice group
config/versions/uClibc.in:1291:warning: choice value used outside its choice group
config/versions/uClibc.in:1315:warning: choice value used outside its choice group
config/versions/uClibc.in:1340:warning: choice value used outside its choice group
config/versions/uClibc.in:1363:warning: choice value used outside its choice group
config/versions/uClibc.in:1386:warning: choice value used outside its choice group
config/versions/uClibc.in:1409:warning: choice value used outside its choice group
config/versions/uClibc.in:1432:warning: choice value used outside its choice group
config/versions/uClibc.in:1455:warning: choice value used outside its choice group
config/versions/uClibc.in:1478:warning: choice value used outside its choice group
config/versions/uClibc.in:1501:warning: choice value used outside its choice group
config/versions/uClibc.in:1524:warning: choice value used outside its choice group
config/versions/uClibc.in:1547:warning: choice value used outside its choice group
config/versions/uClibc.in:1570:warning: choice value used outside its choice group
config/versions/uClibc.in:1593:warning: choice value used outside its choice group
config/versions/uClibc.in:877:warning: choice value used outside its choice group
config/versions/uClibc.in:882:warning: choice value used outside its choice group
config/versions/uClibc.in:888:warning: choice value used outside its choice group
config/versions/uClibc.in:905:warning: choice value used outside its choice group
config/versions/uClibc.in:908:warning: choice value used outside its choice group
config/versions/uClibc.in:911:warning: choice value used outside its choice group
config/versions/uClibc.in:914:warning: choice value used outside its choice group
config/versions/uClibc.in:987:warning: choice value used outside its choice group
config/versions/uClibc.in:990:warning: choice value used outside its choice group
config/versions/uClibc.in:993:warning: choice value used outside its choice group
config/versions/uClibc.in:997:warning: choice value used outside its choice group
config/versions/uClibc.in:1001:warning: choice value used outside its choice group
config/versions/uClibc.in:1005:warning: choice value used outside its choice group
config/versions/uClibc.in:1029:warning: choice value used outside its choice group
config/versions/uClibc.in:1054:warning: choice value used outside its choice group
config/versions/uClibc.in:1078:warning: choice value used outside its choice group
config/versions/uClibc.in:899:warning: choice default symbol 'UCLIBC_DEVEL_VCS_git' is not contained in the choice
config/versions/uClibc.in:984:warning: choice default symbol 'UCLIBC_PATCH_GLOBAL' is not contained in the choice
config/versions/uClibc.in:1185:warning: choice default symbol 'UCLIBC_NG_DEVEL_VCS_git' is not contained in the choice
config/versions/uClibc.in:1270:warning: choice default symbol 'UCLIBC_NG_PATCH_GLOBAL' is not contained in the choice
[G...]   aarch64-ol7u9-linux-gnu
```

This happens for all samples, here I just cut the list to the first item.
As result, the list is quite unreadable.

**Comment by cpackham** [comment] 2021-08-10 08:21
Are you building from master? I just tried and It works for me. There definitely were problems like this when I updated kconfig. It could also be stale versions of generated files. In which case re-running `./bootstrap` should sort it out.

**Comment by carlo-bramini** [comment] 2021-08-11 15:06
I cloned latest sources from repository.
So, I'm also forced to run `./bootstrap` because configure script does not exist.

**Comment by cpackham** [comment] 2021-08-12 08:10
It still looks like either kconfig or the files generated by bootstrap are stale. Try the following

````
cd crosstool-ng
git clean -fxd
git pull
./bootstrap
./configure --enable-local
make
./ct-ng list-samples
````

**Comment by carlo-bramini** [comment] 2021-08-13 09:23
This is my output after doing those commands:

```
Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$ git clean -fxd
Eliminazione di Makefile.in in corso
Eliminazione di aclocal.m4 in corso
Eliminazione di build/ in corso
Eliminazione di config.h.in in corso
Eliminazione di config/gen/ in corso
Eliminazione di config/versions/ in corso
Eliminazione di configure in corso
Eliminazione di kconfig/Makefile.in in corso
Eliminazione di maintainer/package-versions in corso
Eliminazione di verbatim-data.mk in corso
```
translated means:
`Eliminazione di Makefile.in in corso` -> `Deleting Makefile.it`

```
Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$ git pull
Già aggiornato.
```
translated means:
`Già aggiornato.` -> `Up to date.`


```
Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$ ./bootstrap
INFO  :: *** Generating package version descriptions
INFO  :: Master packages: android-ndk autoconf automake avr-libc binutils bison cloog dtc duma elf2flt expat gcc gdb gettext glibc glibc-ports gmp gnuprumcu isl libelf libiconv libtool linux ltrace m4 make mingw-w64 moxiebox mpc mpfr musl ncurses newlib newlib-nano picolibc strace uClibc zlib
INFO  :: Generating 'config/versions/android-ndk.in'
INFO  :: Generating 'config/versions/autoconf.in'
INFO  :: Generating 'config/versions/automake.in'
INFO  :: Generating 'config/versions/avr-libc.in'
INFO  :: Generating 'config/versions/binutils.in'
INFO  :: Generating 'config/versions/bison.in'
INFO  :: Generating 'config/versions/cloog.in'
INFO  :: Generating 'config/versions/dtc.in'
INFO  :: Generating 'config/versions/duma.in'
INFO  :: Generating 'config/versions/elf2flt.in'
INFO  :: Generating 'config/versions/expat.in'
INFO  :: Generating 'config/versions/gcc.in'
INFO  :: Generating 'config/versions/gdb.in'
INFO  :: Generating 'config/versions/gettext.in'
INFO  :: Generating 'config/versions/glibc.in'
INFO  :: Generating 'config/versions/glibc-ports.in'
INFO  :: Generating 'config/versions/gmp.in'
INFO  :: Generating 'config/versions/gnuprumcu.in'
INFO  :: Generating 'config/versions/isl.in'
INFO  :: Generating 'config/versions/libelf.in'
INFO  :: Generating 'config/versions/libiconv.in'
INFO  :: Generating 'config/versions/libtool.in'
INFO  :: Generating 'config/versions/linux.in'
INFO  :: Generating 'config/versions/ltrace.in'
INFO  :: Generating 'config/versions/m4.in'
INFO  :: Generating 'config/versions/make.in'
INFO  :: Generating 'config/versions/mingw-w64.in'
INFO  :: Generating 'config/versions/moxiebox.in'
INFO  :: Generating 'config/versions/mpc.in'
INFO  :: Generating 'config/versions/mpfr.in'
INFO  :: Generating 'config/versions/musl.in'
INFO  :: Generating 'config/versions/ncurses.in'
INFO  :: Generating 'config/versions/newlib.in'
INFO  :: Generating 'config/versions/newlib-nano.in'
INFO  :: Generating 'config/versions/picolibc.in'
INFO  :: Generating 'config/versions/strace.in'
INFO  :: Generating 'config/versions/uClibc.in'
INFO  :: Generating 'config/versions/zlib.in'
INFO  :: *** Generating menu/choice selections
INFO  :: Generating arch.in (choice)
INFO  :: Generating kernel.in (choice)
INFO  :: Generating cc.in (choice)
INFO  :: Generating binutils.in (choice)
INFO  :: Generating libc.in (choice)
INFO  :: Generating debug.in (menu)
INFO  :: Generating comp_tools.in (menu)
INFO  :: Generating comp_libs.in (menu)
INFO  :: *** Gathering the list of data files to install
INFO  :: *** Running autoreconf
INFO  :: *** Done!

Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$ ./configure --enable-local
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-cygwin
checking host system type... x86_64-pc-cygwin
checking whether ln -s works... yes
checking whether install takes --strip-program option... yes
checking for ggrep... no
checking for grep... grep
checking for absolute path to grep... /usr/bin/grep
checking for gegrep... no
checking for egrep... egrep
checking for absolute path to egrep... /usr/bin/egrep
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for sed... /usr/bin/sed
checking for GNU sed >= 4.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking if gcc can static link... yes
checking for ranlib... ranlib
checking for gobjcopy... no
checking for objcopy... objcopy
checking for absolute path to objcopy... /usr/bin/objcopy
checking for gobjdump... no
checking for objdump... objdump
checking for absolute path to objdump... /usr/bin/objdump
checking for greadelf... no
checking for readelf... readelf
checking for absolute path to readelf... /usr/bin/readelf
checking for flex... flex
checking for makeinfo... makeinfo
checking for cut... cut
checking for readlink... readlink
checking for tar... tar
checking for gzip... gzip
checking for bzip2... bzip2
checking for xz... xz
checking for unzip... unzip
checking for help2man... help2man
checking for file... file
checking for which... which
checking for lzip... lzip
checking for wget... wget
checking for curl... curl
checking for meson... meson
checking for ninja... ninja
checking whether to use getconf or sysctl to count CPUs... getconf _NPROCESSORS_ONLN
checking for gpatch... no
checking for patch... patch
checking for absolute path to patch... /usr/bin/patch
checking for bash... /usr/bin/bash
checking for GNU bash >= 3.1... yes
checking for absolute path to gawk... /usr/bin/gawk
checking for GNU awk... yes
checking for make... /usr/bin/make
checking for GNU make >= 3.81... yes
checking for GNU make >= 4.0... yes
checking for libtool... /usr/bin/libtool
checking for GNU libtool >= 2.4... yes
checking for libtoolize... /usr/bin/libtoolize
checking for GNU libtoolize >= 2.4... yes
checking for GNU autoconf >= 2.65... yes
checking for autoreconf... /usr/bin/autoreconf
checking for GNU autoreconf >= 2.63... yes
checking for GNU automake >= 1.15... yes
checking for m4... /usr/bin/m4
checking for GNU m4 >= 1.4.12... yes
checking for python... /usr/bin/python3.7
checking for Python... yes
checking for Python >= 3.4... yes
checking for bison... /usr/bin/bison
checking for bison >= 2.7... yes
checking for dtc... no
checking for cvs... cvs
checking for svn... svn
checking for git... git
checking for gmd5sum... no
checking for md5sum... /usr/bin/md5sum
checking for gsha1sum... no
checking for sha1sum... /usr/bin/sha1sum
checking for gsha256sum... no
checking for sha256sum... /usr/bin/sha256sum
checking for gsha512sum... no
checking for sha512sum... /usr/bin/sha512sum
checking for inline... inline
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for ld used by gcc... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for shared library run path origin... done
checking whether NLS is requested... yes
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ncursesw via pkg-config... yes
checking for working ncursesw/curses.h... yes
checking for working ncursesw.h... no
checking for working ncurses.h... yes
checking for Curses Panel library with ncursesw/panel.h... yes
checking for Curses Menu library with ncursesw/menu.h... yes
checking for build time... Fri Aug 13 10:51:54 2021
checking if the manual needs to be installed... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating paths.sh
config.status: creating kconfig/Makefile
config.status: creating config/configure.in
config.status: creating config.h
config.status: executing depfiles commands

Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$ make
/usr/bin/make  all-recursive
make[1]: ingresso nella directory «/home/Carlo/crosstool-ng»
Making all in kconfig
make[2]: ingresso nella directory «/home/Carlo/crosstool-ng/kconfig»
  LEX      lexer.lex.c
  YACC     parser.tab.c
/usr/bin/make  all-am
make[3]: ingresso nella directory «/home/Carlo/crosstool-ng/kconfig»
  CC       conf.o
  CC       confdata.o
  CC       expr.o
  CC       symbol.o
  CC       preprocess.o
  CC       util.o
  CC       parser.tab.o
  CC       lexer.lex.o
  CCLD     conf.exe
  CC       nconf-nconf.o
  CC       nconf-nconf.gui.o
  CC       nconf-confdata.o
  CC       nconf-expr.o
  CC       nconf-symbol.o
  CC       nconf-preprocess.o
  CC       nconf-util.o
  CC       nconf-parser.tab.o
  CC       nconf-lexer.lex.o
  CCLD     nconf.exe
  CC       mconf.o
  CC       lxdialog/checklist.o
  CC       lxdialog/inputbox.o
  CC       lxdialog/menubox.o
  CC       lxdialog/textbox.o
  CC       lxdialog/util.o
  CC       lxdialog/yesno.o
  CCLD     mconf.exe
make[3]: uscita dalla directory «/home/Carlo/crosstool-ng/kconfig»
make[2]: uscita dalla directory «/home/Carlo/crosstool-ng/kconfig»
make[2]: ingresso nella directory «/home/Carlo/crosstool-ng»
  GEN      ct-ng
  GEN      bash-completion/ct-ng
  GEN      docs/ct-ng.1
make[2]: uscita dalla directory «/home/Carlo/crosstool-ng»
make[1]: uscita dalla directory «/home/Carlo/crosstool-ng»

Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$ ./ct-ng list-samples
Status  Sample name
config/versions/uClibc.in:1163:warning: choice value used outside its choice group
config/versions/uClibc.in:1168:warning: choice value used outside its choice group
config/versions/uClibc.in:1174:warning: choice value used outside its choice group
config/versions/uClibc.in:1191:warning: choice value used outside its choice group
config/versions/uClibc.in:1194:warning: choice value used outside its choice group
config/versions/uClibc.in:1197:warning: choice value used outside its choice group
config/versions/uClibc.in:1200:warning: choice value used outside its choice group
config/versions/uClibc.in:1273:warning: choice value used outside its choice group
config/versions/uClibc.in:1276:warning: choice value used outside its choice group
config/versions/uClibc.in:1279:warning: choice value used outside its choice group
config/versions/uClibc.in:1283:warning: choice value used outside its choice group
config/versions/uClibc.in:1287:warning: choice value used outside its choice group
config/versions/uClibc.in:1291:warning: choice value used outside its choice group
config/versions/uClibc.in:1315:warning: choice value used outside its choice group
config/versions/uClibc.in:1340:warning: choice value used outside its choice group
config/versions/uClibc.in:1363:warning: choice value used outside its choice group
config/versions/uClibc.in:1386:warning: choice value used outside its choice group
config/versions/uClibc.in:1409:warning: choice value used outside its choice group
config/versions/uClibc.in:1432:warning: choice value used outside its choice group
config/versions/uClibc.in:1455:warning: choice value used outside its choice group
config/versions/uClibc.in:1478:warning: choice value used outside its choice group
config/versions/uClibc.in:1501:warning: choice value used outside its choice group
config/versions/uClibc.in:1524:warning: choice value used outside its choice group
config/versions/uClibc.in:1547:warning: choice value used outside its choice group
config/versions/uClibc.in:1570:warning: choice value used outside its choice group
config/versions/uClibc.in:1593:warning: choice value used outside its choice group
config/versions/uClibc.in:877:warning: choice value used outside its choice group
config/versions/uClibc.in:882:warning: choice value used outside its choice group
config/versions/uClibc.in:888:warning: choice value used outside its choice group
config/versions/uClibc.in:905:warning: choice value used outside its choice group
config/versions/uClibc.in:908:warning: choice value used outside its choice group
config/versions/uClibc.in:911:warning: choice value used outside its choice group
config/versions/uClibc.in:914:warning: choice value used outside its choice group
config/versions/uClibc.in:987:warning: choice value used outside its choice group
config/versions/uClibc.in:990:warning: choice value used outside its choice group
config/versions/uClibc.in:993:warning: choice value used outside its choice group
config/versions/uClibc.in:997:warning: choice value used outside its choice group
config/versions/uClibc.in:1001:warning: choice value used outside its choice group
config/versions/uClibc.in:1005:warning: choice value used outside its choice group
config/versions/uClibc.in:1029:warning: choice value used outside its choice group
config/versions/uClibc.in:1054:warning: choice value used outside its choice group
config/versions/uClibc.in:1078:warning: choice value used outside its choice group
config/versions/uClibc.in:899:warning: choice default symbol 'UCLIBC_DEVEL_VCS_git' is not contained in the choice
config/versions/uClibc.in:984:warning: choice default symbol 'UCLIBC_PATCH_GLOBAL' is not contained in the choice
config/versions/uClibc.in:1185:warning: choice default symbol 'UCLIBC_NG_DEVEL_VCS_git' is not contained in the choice
config/versions/uClibc.in:1270:warning: choice default symbol 'UCLIBC_NG_PATCH_GLOBAL' is not contained in the choice
[L...]   aarch64-ol7u9-linux-gnu


Carlo@LAPTOP-658U9K2I ~/crosstool-ng
$
```

...and here I pressed `CTRL-C` for stopping the list.
I hope you will find this report useful.

**Comment by cpackham** [comment] 2021-08-13 10:58
Hmm still can't reproduce it here.

Could you provide a bit more info about your environment (os version shell
etc).

Also post the output of `git remote show origin` and `git rev-parse HEAD`
and attach config/versions/uClibc.in

**Comment by carlo-bramini** [comment] 2021-08-14 13:15
I'm using CYGWIN on Windows 10.
Windows 10 is 64 bit.
I tested both 32bit and 64bit of CYGWIN, same result.

These are the packages that I have installed:

```
Carlo@LAPTOP-658U9K2I ~
$ uname -a
CYGWIN_NT-10.0 LAPTOP-658U9K2I 3.2.0(0.340/5/3) 2021-03-29 08:42 x86_64 Cygwin

Carlo@LAPTOP-658U9K2I ~
$ help2man --version
GNU help2man 1.47.4

Copyright (C) 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2009, 2010,
2011, 2012, 2013, 2014, 2015 Free Software Foundation, Inc.
Questo è software libero; si vedano i sorgenti per le condizioni di copia.
NON c'è alcuna garanzia; neppure di COMMERCIABILITÀ o di IDONEITÀ A UNO
SCOPO PARTICOLARE.

Scritto da Brendan O'Dea <bod@debian.org>

Carlo@LAPTOP-658U9K2I ~
$ pkg-config --modversion ncurses
6.1.20190727

Carlo@LAPTOP-658U9K2I ~
$ flex --version
flex 2.6.4

Carlo@LAPTOP-658U9K2I ~
$ bison --version
bison (GNU Bison) 3.0.4
Scritto da Robert Corbett e Richard Stallman.

Copyright (C) 2015 Free Software Foundation, Inc.
Questo e' software libero; vedere il sorgente per le condizioni cui e'
sottoposta la copia. NON c'è ALCUNA garanzia, neanche di
COMMERCIABILITA` o di ADEGUATEZZA AD UN PARTICOLARE SCOPO.

Carlo@LAPTOP-658U9K2I ~
$ python3 --version
Python 3.8.10

Carlo@LAPTOP-658U9K2I ~
$ curl --version
curl 7.78.0 (x86_64-pc-cygwin) libcurl/7.78.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.1) libssh2/1.9.0 nghttp2/1.44.0 libgsasl/1.8.0 OpenLDAP/2.5.6
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli Debug gsasl GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP TrackMemory UnixSockets zstd
```
I have to say that I had noticed this thing also when I submitted PR #1133 two years ago.

**Comment by cpackham** [comment] 2021-08-15 07:35
Hmm that's not an environment I can easily replicate. Could you attach `config/versions/uClibc.in` from your failure. I suspect that something in your environment (or possibly cygwin's bash shell) is messing up the way the files are generated by ./bootstrap

**Comment by carlo-bramini** [comment] 2021-08-15 20:57
[uClibc.in.txt](https://github.com/crosstool-ng/crosstool-ng/files/6988882/uClibc.in.txt)

I just renamed it to .txt otherwise github web refuses to upload.
Thank you.

**Comment by cpackham-atlnz** [comment] 2021-08-18 08:19
So somehow your `uClibc.in` has got duplicated sections

```
$ diff -u config/versions/uClibc.in cario.uClibc.in
--- config/versions/uClibc.in   2021-08-15 19:43:24.123838888 +1200
+++ cario.uClibc.in     2021-08-18 20:01:38.438771634 +1200
@@ -22,12 +22,25 @@
     help
       uClibc from uclibc.org.
 
+config UCLIBC_USE_UCLIBC_ORG
+    bool "uclibc.org"
+    depends on OBSOLETE
+    help
+      uClibc from uclibc.org.
+
+config UCLIBC_USE_UCLIBC_NG_ORG
+    bool "uclibc-ng.org"
+    help
+      uClibc from uclibc-ng.org.
+
 endchoice
 
 config UCLIBC_USE
     string
     default "UCLIBC_NG" if UCLIBC_USE_UCLIBC_NG_ORG
     default "UCLIBC" if UCLIBC_USE_UCLIBC_ORG
+    default "UCLIBC" if UCLIBC_USE_UCLIBC_ORG
+    default "UCLIBC_NG" if UCLIBC_USE_UCLIBC_NG_ORG
 
 
 if UCLIBC_USE_UCLIBC_NG_ORG
@@ -850,6 +863,827 @@
 
 
 endif
... many more duplicated sections
```

I'm going out on a limb and saying that somehow given the vagaries of cygwin and windows file system interaction it's probably ending up finding `packages/uClibc/package.desc`, `packages/uClibc-ng/package.desc` as 4 files instead of 2. Possibly because cygwin is presenting both `uClibc` and `uclibc` as paths.

Either that or or somehow you've ended up with extra `package.desc` files that the `git clean -fxd` was unable to dispose of.

**Comment by cpackham** [comment] 2021-08-18 08:21
So somehow your `uClibc.in` has got duplicated sections

```
$ diff -u config/versions/uClibc.in cario.uClibc.in
--- config/versions/uClibc.in   2021-08-15 19:43:24.123838888 +1200
+++ cario.uClibc.in     2021-08-18 20:01:38.438771634 +1200
@@ -22,12 +22,25 @@
     help
       uClibc from uclibc.org.
 
+config UCLIBC_USE_UCLIBC_ORG
+    bool "uclibc.org"
+    depends on OBSOLETE
+    help
+      uClibc from uclibc.org.
+
+config UCLIBC_USE_UCLIBC_NG_ORG
+    bool "uclibc-ng.org"
+    help
+      uClibc from uclibc-ng.org.
+
 endchoice
 
 config UCLIBC_USE
     string
     default "UCLIBC_NG" if UCLIBC_USE_UCLIBC_NG_ORG
     default "UCLIBC" if UCLIBC_USE_UCLIBC_ORG
+    default "UCLIBC" if UCLIBC_USE_UCLIBC_ORG
+    default "UCLIBC_NG" if UCLIBC_USE_UCLIBC_NG_ORG
 
 
 if UCLIBC_USE_UCLIBC_NG_ORG
@@ -850,6 +863,827 @@
 
 
 endif
... many more duplicated sections
```

I'm going out on a limb and saying that somehow given the vagaries of cygwin and windows file system interaction it's probably ending up finding `packages/uClibc/package.desc`, `packages/uClibc-ng/package.desc` as 4 files instead of 2. Possibly because cygwin is presenting both `uClibc` and `uclibc` as paths.

Either that or or somehow you've ended up with extra `package.desc` files that the `git clean -fxd` was unable to dispose of.

**Comment by carlo-bramini** [comment] 2021-08-31 13:27
I compiled also under Debian with WSL2 and actually the generated files are all identical except uClibc.in

**Comment by carlo-bramini** [comment] 2021-09-01 19:45
I enable the debug messages and I created two files with the strings printed into Debian and CYGWIN.
The differences starts when it starts to handle uClibc.
Unfortunately, between:
`INFO  :: Generating 'config/versions/uClibc.in'`
and:
`DEBUG :: Setting iterator over 'fork' to 'uClibc-ng uClibc uClibc uClibc-ng'`
there are no useful information, but perhaps you may have an idea from these logs.

[Cygwin.txt](https://github.com/crosstool-ng/crosstool-ng/files/7093881/Cygwin.txt)
[Debian.txt](https://github.com/crosstool-ng/crosstool-ng/files/7093883/Debian.txt)

**Comment by carlo-bramini** [comment] 2022-09-06 13:20
This bug doesn't happen anymore on CYGWIN.
I don't know if it had been fixed by some changes to crosstool-ng or CYGWIN just improved, but now using `list-samples` produces a clean output.

**Comment by cpackham** [comment] 2023-07-15 23:36
Closing as it appears to have been fixed. Not clear how but nothing further to investigate

**Closed by cpackham** 2023-07-15 23:36 UTC
