### ISSUE TITLE
GDB fails to build on Canadian Cross  

### ISSUE THREAD

**Issue by c-grant** [crosstool-ng/crosstool-ng#2001] opened 2023-08-03 02:06 UTC
Attempting to build m68k-unknown-elf which I stated with from the sample.
I added GDB support.
Sample builds fine without gdb (Canadian).

crosstool-NG version: 1.25.0.209_465207b (pulled from git)
OS & version: Ubuntu 22.04.1 LTS

Files:
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12246119/build.log)
[m68k.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/12246122/m68k.config.txt)

Compilers

[EXTRA] Dumping internal crosstool-NG configuration
[EXTRA] Building a toolchain for:
[EXTRA] build = x86_64-pc-linux-gnu
[EXTRA] host = x86_64-w64-mingw32
[EXTRA] target = m68k-unknown-elf

Seems to be a linker issue missing a library.

Tail of log
[ALL  ]    /usr/bin/x86_64-w64-mingw32-ld: ../readline/readline/libreadline.a(terminal.o):/home/vboxuser/CT-NG/m68k/.build/HOST-x86_64-w64-mingw32/m68k-unknown-elf/src/gdb/readline/readline/terminal.c:791: more undefined references to `__imp_tputs' follow

[ERROR]    collect2: error: ld returned 1 exit status

[ERROR]    make[3]: *** [Makefile:2149: gdb.exe] Error 1

[ALL  ]    make[3]: Leaving directory '/home/vboxuser/CT-NG/m68k/.build/HOST-x86_64-w64-mingw32/m68k-unknown-elf/build/build-gdb-cross/gdb'

**Comment by KirillSmirnov** [comment] 2023-08-03 09:47
Duplicate of #1982 

ncurses version <= 6.2 should be fine (assuming already applied PR #2000). ncurses >= 6.3 needs extra care if being built as static on mingw64.

**Comment by cpackham** [comment] 2023-10-29 02:42
looks like this might be fixed. Can anyone confirm?

**Comment by KirillSmirnov** [comment] 2023-10-29 12:21
Works for me on the latest git master.

**Comment by cpackham** [comment] 2023-11-14 21:54
Closing based on the above comment

**Closed by cpackham** 2023-11-14 21:54 UTC
