### ISSUE TITLE
OSX doesn't support building `-static` binaries

### ISSUE THREAD

**Issue by johnjelinek** [crosstool-ng/crosstool-ng#396] opened 2016-05-27 20:37 UTC
http://stackoverflow.com/a/5259427/979315
```
../crosstool-ng-1.22.0/ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20160527.153231
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Checking that gcc can compile a trivial statically linked program (CT_WANTS_STATIC_LINK)'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@554]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/Volumes/CrossTool2NG/crosstool-ng-1.22.0/docs/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 0:04.00)
[00:05] / make: *** [build] Error 1
```

**Comment by johnjelinek** [comment] 2016-05-27 20:52
https://developer.apple.com/library/mac/qa/qa1118/_index.html

**Comment by bhundven** [comment] 2016-05-27 21:13
Yup. We don't support static linking on mac os x, and that is fixed in the master git branch (which I hope we can get reviews done so we can release 1.23!). We don't support it, because apple doesn't support it.
And so. Won't fix.

**Closed by bhundven** 2016-05-27 21:13 UTC
Labels: wontfix

**Comment by johnjelinek** [comment] 2016-05-27 21:22
@bhundven: I should still be able to build though, right? I've commented out those static checking tests. I just need the `arm-unknown-linux-gnueabihf` linker.

**Comment by johnjelinek** [comment] 2016-05-27 22:04
oh boo:
```
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    clang: error: unsupported option '-static-libgcc'
[ERROR]    make[3]: *** [gcov] Error 1
[ERROR]    clang: error: unsupported option '-static-libgcc'
[ERROR]    make[3]: *** [gcov-dump] Error 1
[ERROR]    make[2]: *** [all-gcc] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@537]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@112]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/Volumes/CrossTool2NG/crosstool-ng-1.22.0/docs/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 27:46.00)
[27:46] / make[1]: *** [build] Error 2
make: *** [build.4] Error 2
```

**Comment by bhundven** [comment] 2016-05-27 22:07
Just go through your config and disable anything that enables static linking.

**Comment by MikeMitterer** [comment] 2017-01-04 15:27
I gave up. It's really sad! 
> crosstool-NG aims at building toolchains 

You guys forgot to mention that this excludes Mac! It seems to be Linux only.

Have you ever tried ct-ng for Raspberry on Mac - I assume not!

**Comment by mingwandroid** [comment] 2017-01-04 17:55
Why do you think you need statically linked cross toolchain executables to build raspberry pi software on a Mac? 

You don't and Apple don't support it anyway.

**Comment by mingwandroid** [comment] 2017-01-04 17:55
I forgot to say, yes I have built this variety of toolchain.

**Comment by MikeMitterer** [comment] 2017-01-05 12:01
@stilor You think I'm trolling just because I criticize the current situation???? Check out the forums where people try t compile a cross compiler for Raspberry on Mac and most of them give up because it's so complicated and error prone. 

Finally yesterday I successfully compile a gcc 4.9.3 on my Mac but this took me all in all about 4 or 5 work days with several attempts to do so. How many developers are out there with the same frustrating facts. I read in the forums that they switch to Linux just because Debian provides pre-compiled cross compilers. 

And again - I'm not trolling but open source or not - the application must either work or there must be a clear statement that it doesn't work on a certain platform.

**Comment by bhundven** [comment] 2017-01-05 16:46
Look, we don't support static building on mac os, because Apple does not support static linking on mac os x/macOS. Mac OS has always been experimental in crosstool-ng. Search the mailing list, we've had this discussion before. As I stated before in this issue, in the next release we have fixes that check the build-computer if it is mac os and disable the static linking options. Now we are working towards releasing 1.23 soon. It's been delayed for a while, but those changes are in the master branch.

**Comment by stilor** [comment] 2017-01-05 16:59
On 01/05/2017 04:01 AM, Mike Mitterer wrote:
>
> @stilor <https://github.com/stilor> You think I'm trolling just 
> because I criticize the current situation???? Check out the forums 
> where people try t compile a cross compiler for Raspberry on Mac and 
> most of them give up because it's so complicated and error prone.
>
There's a difference between a criticism and an attitude. Criticism is 
constructive, attitude is just about venting off or blaming.
I could hardly see how your "you guys forgot to mention" can be 
perceived as constructive.
>
> Finally yesterday I successfully compile a gcc 4.9.3 on my Mac but 
> this took me all in all about 4 or 5 work days with several attempts 
> to do so. How many developers are out there with the same frustrating 
> facts. I read in the forums that they switch to Linux just because 
> Debian provides pre-compiled cross compilers.
>
Let me summarize: we have a closed-source OS that one cannot even 
install in emulator without buying a machine from Apple. I don't have a 
MacBook. So, you want me to spend MY money to solve YOUR problem? If any 
of those many developers stuck with MacOS, you included, comes up with a 
patch, I'll be happy to review and integrate it.

Since you mention "work days", I assume you're using ct-ng in your line 
of employment. Perhaps your employer can then sponsor somebody to 
implement what you need in ct-ng.

My involvement with ct-ng started when I needed some features in ct-ng 
that I needed for my day job. However, I am not getting paid for working 
on ct-ng; am working on it in my spare time. Therefore, my priorities in 
ct-ng are the tasks that either make my life easier, or are looking 
interesting to me.
>
> And again - I'm not trolling but open source or not - the application 
> must either work or there must be a clear statement that it doesn't 
> work on a certain platform.
>
And again, you're welcome to submit patches to improve ct-ng 
documentation. Please don't forget to make the list of unsupported 
platforms exhaustive: test on non-x86 Linuxes (various distributions), 
{Free,Open,Net,Dragonfly}BSD on all their respective architectures, 
Solaris, HP-UX, ...

**Comment by FnuGk** [comment] 2017-04-20 15:17
This seems to be caused by the fact that on mac gcc is an alias for clang. 
Installing gcc (through homebrew) and compiling using the real gcc which should be named gcc-5 or gcc-6 should do the trick. However i cant find a way to tell crosstools that i want to use another compiler for the build-machine (change gcc to gcc-5) i have tried running `CC=gcc-5 CXX=g++5 ct-ng build` as you normally would to override it but crosstools seems to just ignore it and call gcc(clang).
Setting the postfix on the build-machine tuple to ´-5´ also seems to be ignored or atleast not do as i expected

Anyone know of a way to set what compiler to use for the build-machine?

**Comment by stilor** [comment] 2017-04-20 16:20
Set "build tools prefix/suffix" in the config. 
I plan to change this in the future to accept CC/CXX and other variables in ct-ng.

**Comment by FnuGk** [comment] 2017-04-20 17:06
i have sat suffix to `-5` to signify i want to compile using `gcc-5` but i can see in `build.log` that it just calls `gcc` which really is just clang:

```
[DEBUG]  Checking that we can run gcc -v
[DEBUG]    ==> Executing: 'x86_64-build_apple-darwin16.3.0-gcc' '-v'
[DEBUG]    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
[DEBUG]    Apple LLVM version 8.1.0 (clang-802.0.38)
[DEBUG]    Target: x86_64-apple-darwin16.3.0
[DEBUG]    Thread model: posix
[DEBUG]    InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

which matches the output from running either `gcc -v` or `clang -v` while i expected the output to be the same as runing `gcc-5 -v` which gives:

```
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@5/5.4.0_1/libexec/gcc/x86_64-apple-darwin15.6.0/5.4.0/lto-wrapper
Target: x86_64-apple-darwin15.6.0
Configured with: ../configure --build=x86_64-apple-darwin15.6.0 --prefix=/usr/local/Cellar/gcc@5/5.4.0_1 --libdir=/usr/local/Cellar/gcc@5/5.4.0_1/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl@0.14 --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --disable-werror --with-pkgversion='Homebrew GCC 5.4.0_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --enable-plugin --disable-nls --enable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
Thread model: posix
gcc version 5.4.0 (Homebrew GCC 5.4.0_1)
```

**Comment by stilor** [comment] 2017-04-20 17:37
Find where it sets up the tools in the log. For me, it printed this:

````
[DEBUG]  Making build system tools available
[DEBUG]    'x86_64-build_pc-linux-gnu-ar' -> '/usr/bin/ar'
[DEBUG]  ==> Executing: 'chmod' '700' '/home/avn/work/ctng/crosstool-ng/.build/avr/buildtools/bin/x86_64-build_pc-linux-gnu-ar'
[DEBUG]    'x86_64-build_pc-linux-gnu-as' -> '/usr/bin/as'
[DEBUG]  ==> Executing: 'chmod' '700' '/home/avn/work/ctng/crosstool-ng/.build/avr/buildtools/bin/x86_64-build_pc-linux-gnu-as'
[DEBUG]    Missing: 'x86_64-pc-linux-gnu-dlltool-5' or 'x86_64-pc-linux-gnu-dlltool' or 'dlltool' : not required.
[DEBUG]    'x86_64-build_pc-linux-gnu-gcc' -> '/usr/bin/gcc-5'
````
Check what it linked to `gcc-5`, not to `gcc` in your case (if ct-ng cannot find the tool with the specified suffix, it falls back to using no suffix). Of course, make sure `gcc-5` is in your $PATH.

**Comment by FnuGk** [comment] 2017-04-20 19:54
It appears to first set it correctly to `/usr/local/bin/gcc-5` but then right after it sets it back to `/usr/bin/gcc`

note that apple provided fake gcc lives in `/usr/bin` and homebrew packages lives lives in `/usr/local/bin` so it seems to fallback to no suffix even though it does find it. Am i missing something?

```
[DEBUG]  Making build system tools available
[DEBUG]    'x86_64-build_apple-darwin16.3.0-ar' -> '/usr/bin/ar'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-ar'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-as' -> '/usr/bin/as'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-as'
[DEBUG]    Missing: 'x86_64-apple-darwin16.3.0-dlltool-5' or 'x86_64-apple-darwin16.3.0-dlltool' or 'dlltool' : not required.
[DEBUG]    'x86_64-build_apple-darwin16.3.0-gcc' -> '/usr/local/bin/gcc-5'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-gcc'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-g++' -> '/usr/local/bin/g++-5'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-g++'
[DEBUG]  Testing '! (  = y )'
[DEBUG]    Missing: 'x86_64-apple-darwin16.3.0-gnatbind-5' or 'x86_64-apple-darwin16.3.0-gnatbind' or 'gnatbind' : not required.
[DEBUG]    Missing: 'x86_64-apple-darwin16.3.0-gnatmake-5' or 'x86_64-apple-darwin16.3.0-gnatmake' or 'gnatmake' : not required.
[DEBUG]    'x86_64-build_apple-darwin16.3.0-ld' -> '/usr/bin/ld'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-ld'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-nm' -> '/usr/bin/nm'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-nm'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-objcopy' -> '/Volumes/cross_img/out/.build/tools/bin/objcopy'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-objcopy'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-objdump' -> '/Volumes/cross_img/out/.build/tools/bin/objdump'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-objdump'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-ranlib' -> '/usr/bin/ranlib'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-ranlib'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-strip' -> '/usr/bin/strip'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-strip'
[DEBUG]    Missing: 'x86_64-apple-darwin16.3.0-windres-5' or 'x86_64-apple-darwin16.3.0-windres' or 'windres' : not required.
[DEBUG]    'x86_64-build_apple-darwin16.3.0-ar' -> '/usr/bin/ar'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-ar'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-as' -> '/usr/bin/as'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-as'
[DEBUG]    Missing: 'x86_64-apple-darwin16.3.0-dlltool' or 'x86_64-apple-darwin16.3.0-dlltool' or 'dlltool' : not required.
[DEBUG]    'x86_64-build_apple-darwin16.3.0-gcc' -> '/usr/bin/gcc'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-gcc'
[DEBUG]    'x86_64-build_apple-darwin16.3.0-g++' -> '/usr/bin/g++'
[DEBUG]  ==> Executing: 'chmod' '700' '/Volumes/cross_img/out/.build/arm-unknown-linux-gnueabi/buildtools/bin/x86_64-build_apple-darwin16.3.0-g++'
```

full build.log [here](https://gist.github.com/FnuGk/774f0470da6c286a5d4e665cc8e67833)

**Comment by stilor** [comment] 2017-04-21 04:47
This does seem like a bug. I created a new issue to track it.

**Comment by tjpeden** [comment] 2017-07-07 03:15
I'm disappointed in the devs in this issue. Being hostile with your users just because their frustrated is very distasteful. I'm not defending that user nor do I condone his attitude, but please take the high road. I'm searching around for resolutions to my own crosstool-ng issues and this thread put a very bad taste in my mouth. You can certainly find the constructive criticism in his statement. Add more documentation to make the situation on macOS more clear. I can certainly say that using this software is definitely not well documented for macOS from what I can tell so far. Please don't take this as hostility from me, I am giving you what I would consider constructive criticism. That being said, I do appreciate what you are trying to do here, so keep it up.

**Comment by stilor** [comment] 2017-07-07 04:53
You are certainly welcome to submit PRs with enhancements, both for the code and the documentation. Right now, I can use the fingers to count the number of PRs submitted by macOS users, and I probably won't even need the other hand. However, if there's somebody claiming that "the devs" don't do enough, it is most certainly a macOS user.

If you haven't noticed, "the devs" body currently consists of a single person: me. And I don't even use macOS myself. Please re-read what you perceived as "being hostile": the user made *demands* on what I should do in my spare time. To quote myself: **I am not getting paid for working on ct-ng; am working on it in my spare time**.

Thanks for teaching me a lesson, though. I'll consider officially retiring support for macOS in the next release unless there's a volunteer that will investigate all macOS complaints.
