### ISSUE TITLE
bootstrap script issue with CDPATH set.

### ISSUE THREAD

**Issue by tsdunc** [crosstool-ng/crosstool-ng#849] opened 2017-10-23 20:29 UTC
crosstool-NG version: latest master (6a8eb24df62e)
host OS and its version: Ubutnu 14.04

bootstrap outptut:
INFO  :: *** Generating package version descriptions
./bootstrap: line 456: packages//home/tsduncan/crosstool-ng/packages/package.desc: No such file or directory
./bootstrap: line 504: /home/tsduncan/crosstool-ng/packages: syntax error: operand expected (error token is "/home/tsduncan/crosstool-ng/packages")
INFO  :: *** Generating menu/choice selections
INFO  :: Generating arch.in
INFO  :: Generating kernel.in
INFO  :: Generating cc.in
INFO  :: Generating binutils.in
INFO  :: Generating libc.in
INFO  :: Generating debug.in
INFO  :: Generating comp_tools.in
INFO  :: *** Running autoconf
INFO  :: *** Done!

This can be avoided by adding prepending ./ to the cd directory as in this patch:
diff --git a/bootstrap b/bootstrap
index 52b27ed4..3a2f0b4c 100755
--- a/bootstrap
+++ b/bootstrap
@@ -557,7 +557,7 @@ enter_fork()
         info[repository_url]=${info[repository]#* }
     fi
 
-    versions=`cd packages/${fork} && \
+    versions=`cd ./packages/${fork} && \
         for f in */version.desc; do [ -r "${f}" ] && echo "${f%/version.desc}"; done`
     versions=`sort_versions ${versions}`
 
@@ -604,7 +604,7 @@ gen_packages()
     local -A pkg_forks pkg_milestones pkg_nforks pkg_relevantpattern
     local -a pkg_masters pkg_all pkg_preferred
 
-    pkg_all=( `cd packages && \
+    pkg_all=( `cd ./packages && \
         ls */package.desc 2>/dev/null | \
         while read f; do [ -r "${f}" ] && echo "${f%/package.desc}"; done | \
         xargs echo` )

**Comment by stilor** [comment] 2017-10-23 21:20
Duplicate of #842

**Closed by stilor** 2017-10-23 21:20 UTC
