### ISSUE TITLE
error: panel library not found

### ISSUE THREAD

**Issue by reeslabree** [crosstool-ng/crosstool-ng#1866] opened 2022-12-07 21:36 UTC
Exact Error: 
```
checking for Curses Panel library with ncursesw/panel.h... no
configure: error: panel library not found
```

crosstool-NG version: `1.25.0`
host OS and its version: `MacOS Monterey 12.1`
`.config`:
```
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /opt/homebrew/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... aarch64-apple-darwin21.2.0
checking host system type... aarch64-apple-darwin21.2.0
checking whether ln -s works... yes
checking whether install takes --strip-program option... yes
checking for ggrep... no
checking for grep... grep
checking for absolute path to grep... /usr/bin/grep
checking for gegrep... no
checking for egrep... egrep
checking for absolute path to egrep... /usr/bin/egrep
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for sed... /opt/homebrew/bin/gsed
checking for GNU sed >= 4.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking for flex... flex
checking for lex output file root... lex.yy
checking for lex library... none needed
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking if bison is the parser generator... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking if gcc can static link... no
checking for ranlib... ranlib
checking for gobjcopy... gobjcopy
checking for absolute path to gobjcopy... /opt/homebrew/opt/binutils/bin/gobjcopy
checking for gobjdump... gobjdump
checking for absolute path to gobjdump... /opt/homebrew/opt/binutils/bin/gobjdump
checking for greadelf... greadelf
checking for absolute path to greadelf... /opt/homebrew/opt/binutils/bin/greadelf
checking for flex... flex
checking for makeinfo... makeinfo
checking for cut... cut
checking for readlink... readlink
checking for tar... tar
checking for gzip... gzip
checking for bzip2... bzip2
checking for xz... xz
checking for unzip... unzip
checking for help2man... help2man
checking for file... file
checking for which... which
checking for lzip... no
checking for wget... wget
checking for curl... curl
checking for meson... no
checking for ninja... no
checking for rsync... rsync
checking whether to use getconf or sysctl to count CPUs... sysctl -n hw.ncpu
checking for gpatch... no
checking for patch... patch
checking for absolute path to patch... /usr/bin/patch
checking whether patch supports --no-backup-if-mismatch... yes
checking for bash... /opt/homebrew/bin/bash
checking for GNU bash >= 3.1... yes
checking for absolute path to gawk... /opt/homebrew/bin/gawk
checking for GNU awk... yes
checking for make... /usr/bin/make
checking for GNU make >= 3.81... yes
checking for GNU make >= 4.0... no
checking for libtool... /opt/homebrew/bin/glibtool
checking for GNU libtool >= 2.4... yes
checking for libtoolize... /opt/homebrew/bin/glibtoolize
checking for GNU libtoolize >= 2.4... yes
checking for GNU autoconf >= 2.71... yes
checking for autoreconf... /opt/homebrew/bin/autoreconf
checking for GNU autoreconf >= 2.71... yes
checking for GNU automake >= 1.16... yes
checking for m4... /usr/bin/gm4
checking for GNU m4 >= 1.4.12... no
checking for python... /opt/homebrew/bin/python3
checking for Python... yes
checking for Python >= 3.4... yes
checking for bison... /usr/bin/bison
checking for bison >= 2.7... no
checking for bison >= 3.0.4... no
checking for dtc... no
checking for cvs... no
checking for svn... no
checking for git... git
checking for gmd5sum... /opt/homebrew/bin/gmd5sum
checking for gsha1sum... /opt/homebrew/bin/gsha1sum
checking for gsha256sum... /opt/homebrew/bin/gsha256sum
checking for gsha512sum... /opt/homebrew/bin/gsha512sum
checking for inline... inline
checking for GNU libc compatible malloc... yes
checking for GNU libc compatible realloc... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for shared library run path origin... done
checking 32-bit host C ABI... no
checking for ELF binary format... no
checking for the common suffixes of directories in the library search path... lib,lib,lib
checking whether NLS is requested... yes
checking for CFPreferencesCopyAppValue... yes
checking for CFLocaleCopyPreferredLanguages... yes
checking for GNU gettext in libc... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for GNU gettext in libintl... no
checking whether to use NLS... no
checking for pkg-config... /opt/homebrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ncursesw via pkg-config... yes
checking for working ncursesw/curses.h... no
checking for working ncursesw.h... no
checking for working ncurses.h... yes
checking for Curses Panel library with ncursesw/panel.h... no
configure: error: panel library not found
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
```

**Comment by TommyMurphyTM1234** [comment] 2022-12-08 19:01
Same issue as this albeit in Arch Linux there:

https://github.com/crosstool-ng/crosstool-ng/issues/1853

Maybe the patch in that issue will help here too?

**Comment by bhundven** [comment] 2022-12-08 20:46
Duplicate of #1853
The issues are similar, though different OSs.

**Closed by bhundven** 2022-12-08 20:46 UTC
