### ISSUE TITLE
crosstool-ng fails with Canadian build

### ISSUE THREAD

**Issue by john-stone-ics** [crosstool-ng/crosstool-ng#436] opened 2016-08-31 05:33 UTC
On Ubuntu 16.04:

 **<get  x86_64-linux-gnu-gcc (v5.4.0) for build >**
# > sudo apt-get -y install build-essentials

 **<get  x86_64-w64-mingw32-gcc  (v5.3.1) for host >**
# > sudo apt-get -y install mingw-64

**<notable .config entries -- see attached build.zip .config file for complete listing >**
CT_ARCH="arm"
CT_ARCH_SUPPORTS_SOFTFP=y
CT_ARCH_CPU="cortex-a9"
CT_ARCH_FPU="neon"
CT_CANADIAN=y
CT_TOOLCHAIN_TYPE="canadian"
CT_BUILD=""
CT_HOST="x86_64-w64-mingw32"
# > ct-ng build

[EXTRA]============================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-w64-mingw32
[EXTRA]      target = arm-ics-linux-gnueabi
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.68s (at 00:21)
[INFO ] ===========================================================

**<many errors here like the following -- see attached build.zip log file for details>**

[ERROR]    libtool:   error: Could not determine the host path corresponding to
[ERROR]    libtool:   error:   '/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/build/build-gettext-host-x86_64-host_w64-mingw32/gettext-runtime/intl/.libs:/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools/complibs-host/lib'
[ERROR]    libtool:   error: Continuing, but uninstalled executables may not work.

**<and finally the hard failure >**

[INFO ]============================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[ERROR]    configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@594]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@271]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@624]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/jss/.local/share/doc/crosstool-ng/crosstool-ng-1.22.0-205-g2b887e4/B - Known issues.txt'
[ERROR]
[ERROR](elapsed: 47:57.16)
[47:59] / make: **\* [/home/jss/.local/bin/ct-ng:152: build] Error 1

[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/446478/build.zip)

**Comment by bhundven** [comment] 2016-08-31 16:27
I got the mingw toolchain built. I'll test the cross-canadian toolchain build tonight.

**Comment by john-stone-ics** [comment] 2016-08-31 18:48
**\<If you look in the build.log file you'll see this line: \>**

[INFO ]  Installing pass-1 core C gcc compiler
[DEBUG]    Entering '/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/build/build-cc-gcc-core-pass-1'

**\<If you go to that directory you'll find the attached config.log file.  In it you will find errors like these:\>**

.build/src/mpfr-3.1.3/src/mpfr-gmp.c:330: undefined reference to `__imp___iob_func'

.build/src/mpfr-3.1.3/src/add1.c:60: undefined reference to `___chkstk_ms'

**\<These errors come from the libmpfr.a, libmpc.a libgmp.a libraries in:\>**

.build/arm-ics-linux-gnueabi/buildtools/complibs-host/lib

**\<This -L path comes from LD_FLAGS environment variable set on the command line that executed configure:\>**

[DEBUG]    ==> Executing: 'CC_FOR_BUILD=x86_64-build_pc-linux-gnu-gcc' 'CFLAGS=-O2 -g -pipe  -I/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools/complibs-host/include' 'CXXFLAGS=-O2 -g -pipe  -I/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools/complibs-host/include' 'LDFLAGS=  -L/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools/complibs-host/lib' 'CFLAGS_FOR_TARGET= -mlittle-endian   -mcpu=cortex-a9  -mfpu=neon -mfloat-abi=softfp ' 'CXXFLAGS_FOR_TARGET= -mlittle-endian   -mcpu=cortex-a9  -mfpu=neon -mfloat-abi=softfp ' 'LDFLAGS_FOR_TARGET= -Wl,-EL ' '/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/src/gcc-5.3.0/configure' '--build=x86_64-build_pc-linux-gnu' '--host=x86_64-build_pc-linux-gnu' '--target=arm-ics-linux-gnueabi' '--prefix=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools' '--with-local-prefix=/home/jss/crosstools-ng/x-tools/arm-ics-linux-gnueabi/arm-ics-linux-gnueabi/sysroot' '--with-sysroot=/home/jss/crosstools-ng/x-tools/arm-ics-linux-gnueabi/arm-ics-linux-gnueabi/sysroot' '--with-newlib' '--enable-threads=no' '--disable-shared' '--with-cpu=cortex-a9' '--with-fpu=neon' '--with-float=softfp' '--with-pkgversion=crosstool-NG crosstool-ng-1.22.0-205-g2b887e4' '--enable-__cxa_atexit' '--disable-libgomp' '--disable-libmudflap' '--disable-libssp' '--disable-libquadmath' '--disable-libquadmath-support' '--with-gmp=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools' '--with-mpfr=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools' '--with-mpc=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools' '--with-isl=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools' '--enable-lto' '--with-host-libstdcxx=-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' '--enable-target-optspace' '--disable-nls' '--disable-multilib' '--enable-languages=c' 

**\<and the fact that gcc configure script puts $LD_FLAGS before $LIBS when building it's conftest.c files.  You can see this by:\>**

#> grep ac_link= .build/src/gcc-5.3.0/configure
ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'

**\<Interestingly enough, if you remove that LD_FLAG so the configure script uses the paths set by --with-gmp, --with-mpfr, and --with-mpc (all of which are set to be the following path): then this gcc configure step passes.  However the build still fails, but at a latter stage.\>**

--with-mpc=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools 
--with-gmp=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools 
--with-mpfr=/home/jss/crosstools-ng/arm-ics-linux-gneuabi/.build/arm-ics-linux-gnueabi/buildtools 

**\<In short it appears that gcc's configure allows LD_FLAGS to override it's --with-gmp, --with_mpfr and --with_mpc configure flags\>**


[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/448044/config.zip)

**Comment by john-stone-ics** [comment] 2016-08-31 18:52
**\<oh, and b.t.w\>**

```
~build/crosstool-ng$ git branch
* master
~build/crosstool-ng$ git rev-parse HEAD
2b887e417a1fceba9229b5189a0e9cf0b547e5bc
```

**Comment by fhunleth** [comment] 2016-09-16 04:10
I can confirm that I'm seeing this issue as well. My build and host are set the same, but I have a different arm target. The details about the error look identical to what I'm seeing. I am able to create working canadian builds for non-Windows platforms.

**Comment by fhunleth** [comment] 2016-09-16 13:37
In case this provides a clue, I'm able to build using the 1.22.0 release, so this must have regressed since then. The defconfig that I'm using looks like:

```
CT_LOCAL_TARBALLS_DIR="${CT_TOP_DIR}/../dl"
CT_SAVE_TARBALLS=y
CT_PREFIX_DIR="${CT_TOP_DIR}/../x-tools/${CT_TARGET}"
# CT_REMOVE_DOCS is not set
CT_LOG_EXTRA=y
CT_ARCH_FLOAT_HW=y
CT_ARCH_arm=y
CT_CANADIAN=y
CT_HOST="x86_64-w64-mingw32"
CT_KERNEL_linux=y
CT_KERNEL_V_3_4=y
CT_BINUTILS_LINKER_LD_GOLD=y
CT_BINUTILS_GOLD_THREADS=y
CT_BINUTILS_LD_WRAPPER=y
CT_LIBC_GLIBC_V_2_21=y
# CT_CC_GCC_SJLJ_EXCEPTIONS is not set
CT_CC_LANG_CXX=y
```

**Comment by mcrapet** [comment] 2016-09-20 14:14
I've successively built a canadian toolchain (build=win64, target=arm, host=linux).
I've followed discussion above and patched:
<pre>
diff --git a/scripts/build/cc/100-gcc.sh b/scripts/build/cc/100-gcc.sh
index db14728..404fcbd 100644
--- a/scripts/build/cc/100-gcc.sh
+++ b/scripts/build/cc/100-gcc.sh
@@ -595,7 +595,7 @@ do_gcc_core_backend() {
     CC_FOR_BUILD="${CT_BUILD}-gcc"                     \
     CFLAGS="${cflags}"                                 \
     CXXFLAGS="${cflags}"                               \
-    LDFLAGS="${core_LDFLAGS[*]}"                       \
+    FIXMELDFLAGS="${core_LDFLAGS[*]}"                       \
     CFLAGS_FOR_TARGET="${CT_TARGET_CFLAGS}"            \
     CXXFLAGS_FOR_TARGET="${CT_TARGET_CFLAGS}"          \
     LDFLAGS_FOR_TARGET="${CT_TARGET_LDFLAGS}"          \
</pre>

It worked (with today's ct-ng git repository).

**Comment by john-stone-ics** [comment] 2016-09-20 17:26
Here is the commit id for scripts/build/cc/100-gcc.sh that is the breaking change:  02d8e4a514773273443c213dab3954bdc626ecbc

**scripts/build/cc: pass FLAGS_FOR_TARGET in do_gcc_core_backend**

**Comment by mcrapet** [comment] 2016-09-21 08:01
Thanks @john-stone-ics!

**Comment by stilor** [comment] 2016-12-01 01:07
@john-stone-ics It isn't breaking, it is rather uncovering the bug that has been in crosstool-ng for quite awhile. The error should be fixed when PR484 is merged - which I'll do shortly. The libtool "errors", AFAIU, are really warnings - since we are not going to run *host* executables on *build* machine anyway.

**Closed by stilor** 2016-12-01 01:07 UTC
Labels: bug, unconfirmed
