### ISSUE TITLE
Canadian cross build seems to be broken

### ISSUE THREAD

**Issue by modbw** [crosstool-ng/crosstool-ng#33] opened 2015-01-15 13:29 UTC
Building a canadian cross toolchains seems to be broken in current head revision. Even the supplied sample fails:
```
$ ct-ng i586-mingw32msvc,i686-none-linux-gnu   LN    config
  MKDIR config.gen
  IN    config.gen/arch.in
  IN    config.gen/kernel.in
  IN    config.gen/cc.in
  IN    config.gen/binutils.in
  IN    config.gen/libc.in
  IN    config.gen/debug.in
  CONF  config/config.in
#
# configuration saved
#

***********************************************************

Initially reported by:
URL:

***********************************************************

Now configured for "i586-mingw32msvc,i686-none-linux-gnu"
$ ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20150115.142754
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[ERROR]  Missing: 'i586-mingw32msvc-ar' or 'i586-mingw32msvc-ar' or 'ar' : either needed!
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@331]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@449]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/data/users/mweisser/projects/sd/MCP/Devices/MCPJ/boot/toolchain/ct-ng/install/share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 0:00.66)
[00:01] / make: *** [build] Error 1

```

**Comment by bhundven** [comment] 2015-01-24 19:26
Could you post a gist/pastebin of the config and log, and I'll attempt to reproduce and see if I can fix it. Thanks!

**Comment by modbw** [comment] 2015-01-26 12:40
Hi

I can post such a config but even the delivered example doesn't work. If I just run

  $ ct-ng i586-mingw32msvc,i686-none-linux-gnu
  $ ct-ng build

I get a build error very early in the process. See my example in the original post. Please let me know if I should post a complete package.

**Comment by bhundven** [comment] 2015-01-26 16:05
@modbw Thanks, I'll try this build today and will report with my results.

**Comment by bhundven** [comment] 2015-01-26 17:46
@modbw Ok, I've never built this particular sample. It seems to me that i586-mingw32msvc toolchain needs to be installed first and in your PATH. @diorcety might be able to confirm this, since he added this sample.

**Comment by modbw** [comment] 2015-01-27 07:05
I think I got it now. I think I have to run ct-ng multiple times for a canadian cross build. I will give it a try if I find some time.

**Comment by bhundven** [comment] 2015-01-28 00:22
Ok. I'm going to close this issue, but do reopen if you still have this specific issue.

**Closed by bhundven** 2015-01-28 00:22 UTC
