### ISSUE TITLE
x86_64 uclibc-ng toolchain generates segfault binaries

### ISSUE THREAD

**Issue by Unturned3** [crosstool-ng/crosstool-ng#1095] opened 2018-11-18 03:57 UTC
I configured crosstool-ng with the default "x86_64-unknown-linux-uclibc" and tried to compile a statically linked "hello world" C program. It successfully compiled but when I tried to run the binary it resulted in a segfault. Crosstool-ng documentation said that uclibc won't work with gcc 5 or above, but I am using the newest uclibc-ng and gcc7.3.0. Any idea what's causing the segfault?
Thanks.

crosstool-ng version: 1.23.0.534-710c8
host OS: Arch Linux (x86_64 4.19.2-arch1-1-ARCH)
[buildlog.gz](https://github.com/crosstool-ng/crosstool-ng/files/2592497/buildlog.gz)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/2592499/config.txt)

**Comment by stilor** [comment] 2018-11-28 06:03
Are you running the compiled program on the host machine? Host machine may not have the required libraries/dynamic linker installed or it may have an incompatible version that crashes; it is expected that you create a ramdisk image with the required libraries. Tools like buildroot can help with that.

For a quick test, you can set up a simple chrooted environment, e.g.:
````
avn@mistral:/tmp$ cp -r ~/x-tools/x86_64-multilib-linux-uclibc/x86_64-multilib-linux-uclibc/sysroot /tmp/yy
avn@mistral:/tmp$ chmod -R +w /tmp/yy
avn@mistral:/tmp$ cat f.c
#include <stdio.h>

int main(void)
{
    printf("hello\n");
    return 0;
}
avn@mistral:/tmp$ ~/x-tools/x86_64-multilib-linux-uclibc/bin/x86_64-multilib-linux-uclibc-gcc -o /tmp/yy/f f.c -O2 -Wall
avn@mistral:/tmp$ sudo chroot /tmp/yy ./f
hello
````

**Comment by Unturned3** [comment] 2018-11-29 05:07
Hello,
I ran the "hello, world" C program inside a QEMU virtual machine, and I compiled it with the "--static" flag. The program was passed to the Linux kernel as the "init" parameter, and the kernel was unable to load it. I also tried you chroot method and it resulted the same segfault. I built crosstool-ng with glibc and compiled a static helloworld, and it ran without any problems both on the host and inside QEMU. 
If a program is compiled statically, then it should be independent from any system libs right?
Thanks for the reply.

**Comment by stilor** [comment] 2018-11-29 21:37
Confirmed, static binaries indeed crash in `__libc_setup_tls`. AFAIU, it crashes in this code:
````
  /* Look through the TLS segment if there is any.  */
  if (_dl_phdr != NULL)
    for (phdr = _dl_phdr; phdr < &_dl_phdr[_dl_phnum]; ++phdr)
      if (phdr->p_type == PT_TLS) /// <--- crashes here because memory at phdr is not mapped
````
From GDB (7 is `PT_TLS`):
````
   0x0000000000401a6a <+46>:    cmp    %rax,%rdx
   0x0000000000401a6d <+49>:    jbe    0x401a96 <__libc_setup_tls+90>
=> 0x0000000000401a6f <+51>:    cmpl   $0x7,(%rax)
   0x0000000000401a72 <+54>:    jne    0x401a90 <__libc_setup_tls+84>
   0x0000000000401a74 <+56>:    mov    0x30(%rax),%r12
...
(gdb) p/x $rax
$1 = 0x400040
````
while readelf shows the program headers as follows:
````
  LOAD           0x001000 0x0000000000401000 0x0000000000401000 0x007f2f 0x007f2f R E 0x1000
  LOAD           0x009000 0x0000000000409000 0x0000000000409000 0x002dc8 0x002dc8 R   0x1000
  LOAD           0x00bf80 0x000000000040cf80 0x000000000040cf80 0x000358 0x003758 RW  0x1000
  TLS            0x00bf80 0x000000000040cf80 0x000000000040cf80 0x000000 0x000008 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
  GNU_RELRO      0x00bf80 0x000000000040cf80 0x000000000040cf80 0x000080 0x000080 R   0x1
````
As one can see, the memory with the program headers themselves (400000..400fff) is not mapped in a static binary.

Feel free to relay this information to uClibc-ng maintainers at https://uclibc-ng.org.

**Comment by stilor** [comment] 2018-11-29 21:44
Closing; the issue is not in crosstool-NG.

**Closed by stilor** 2018-11-29 21:44 UTC

**Comment by stilor** [comment] 2018-11-30 06:35
It may be, or it may be a change in binutils (since it is the linker script which determines how the program segments are created). You can try to roll them back to older versions and see if it helps - if it does, then bisect to the exact release that caused this behavior.
