### ISSUE TITLE
CT_CC_GCC_ENABLE_CXX_FLAGS doesn't seem to have any effect

### ISSUE THREAD

**Issue by FreddieChopin** [crosstool-ng/crosstool-ng#298] opened 2015-12-07 18:27 UTC
In my toolchain for ARM microcontrollers I disable C++ exceptions with `--enable-cxx-flags="-fno-exceptions"` passed to final step of GCC compilation. I tried the same with crosstool-ng, but it doesn't seem to work at all... If I add `"-fno-exceptions"` or `-fno-exceptions` or `\"-fno-exceptions\"`to the CT_CC_GCC_ENABLE_CXX_FLAGS option, the toolchain that gets built has exceptions enabled. I've also searched build.log file for "--enable-cxx-flags=" or "CXXFLAGS_FOR_TARGET" but neither is used...

Is this a bug or am I doing something wrong?

**Comment by FreddieChopin** [comment] 2015-12-07 18:34
Browsing through the code that uses this variable I see nothing wrong there, but I don't know the code at all, so it may not see something obvious...

**Comment by bhundven** [comment] 2015-12-07 18:34
Please post config and build.log. Thanks!

**Comment by FreddieChopin** [comment] 2015-12-07 18:39
I'll have to rebuild it anyway, so I may ask in advance - what string form should I actually enter for the option? `-fno-exceptions`, `"-fno-exceptions"`, `\"-fno-exceptions\"` or maybe something else?

**Comment by bhundven** [comment] 2015-12-07 18:41
As the help message says: Note: just pass in the option _value_, that is only the part that goes after the '=' sign.

So I would think that would be: -fno-exceptions

**Comment by FreddieChopin** [comment] 2015-12-07 18:45
OK, I'm trying without any quotes. But if you need to pass more than one option this way, you have to quote them somehow anyway... I'll upload the build.log when it's done, so in about 25 minutes...

**Comment by bhundven** [comment] 2015-12-07 18:49
Well, you don't have to worry about that.

CT_CC_GCC_ENABLE_CXX_FLAGS is a string: https://github.com/crosstool-ng/crosstool-ng/blob/master/config/cc/gcc.in.2#L3

Then that string is quoted when we add --enable-cxx-flags to $extra_config: https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/build/cc/100-gcc.sh#L732

**Comment by FreddieChopin** [comment] 2015-12-07 19:32
Here's the build.log and the config file I used.
https://www.dropbox.com/s/npoc8vm0sdromu4/build.log.bz2?dl=0&s=sl
https://www.dropbox.com/s/s8vyp3yoshl9758/crosstool.config?dl=0&s=sl

From reading the 100-gcc.sh file I would expect to find some more options, yet they cannot be seen anywhere - for example I think there should be `--disable-libatomic` but this one is missing too...

This finally suggested where's the problem. `do_gcc_for_host()` doesn't use `do_gcc_backend()` for bare-metal target (which I use) to build the final compiler. In that case `do_gcc_core_backend()` is used, and this function doesn't set the `--enable-cxx-flags` option and it doesn't use `${CT_CC_GCC_ENABLE_CXX_FLAGS}`.

**Comment by bhundven** [comment] 2015-12-07 19:36
Interesting point. This might be something I need to wait on until those other two pull requests are merged.

The problem is we have two gcc backends for builds that have to be kept in sync and they have not been. I plan to merge those two backends.

**Comment by bhundven** [comment] 2015-12-07 19:40
I will work on getting those merged today, so I can start working on the solution for this issue and prep for 2-pass gcc build #217.

**Comment by bhundven** [comment] 2016-01-06 06:36
@FreddieChopin Please try out PR #312. This should fix this issue. Please report results back. Thanks!

**Comment by bhundven** [comment] 2016-01-06 18:47
Bleh, nevermind. I was looking at the wrong option. I really need to do a cleanup on 100-gcc.sh.

**Closed** 2016-01-06 19:25 UTC
Labels: bug, confirmed
