### ISSUE TITLE
build fails on zlib

### ISSUE THREAD

**Issue by Charlie25466** [crosstool-ng/crosstool-ng#1935] opened 2023-04-15 23:45 UTC
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
version 1.25.0
op sys RaspberryPi 64 bit desktop running in window hyperv virtual machine on hyper-v Debian 11 64 bit
 uname gives:
    Linux raspberry 5.10.0-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86-64 GNU/Linux

sudo apt install zlib1g installs zlib version 1.2.11 and says it is latest version.
build file says CT_ZLIB_V_1_2_12=y and CT_ZLIB_VERSION="1.2.12"
ct-ng build apparently tries to find v1_2_12, cannot and so tries to extract it.  I think from a downloaded linux distro linux-5.16.9.tar.xz
  I have tried to find it in the distro.  I cannot.
In the build file I find CT_ZLIB_MIRRORS="http://downloads.sourceforge.net/project/libpng/zlib/${CT_ZLIB_VERSION} https://www.zlib.net/"
"http://downloads.sourceforge.net/project/libpng/zlib is an archive for png graphics NOT zlib so this is wrong.  Not sure the impact.

The menu config tool does not options for zlib -- that I can find

I directly modified the .build file with the following:
   T_ZLIB_V_1_2_13=y
   CT_ZLIB_VERSION="1.2.13"

I intended to set versions to 1.2.11 but have verified I set them to 1.2.13 --  log file confirms 1.2.13 is set.  Build log shows it trying to download from http://downloads.sourceforge.net/project/libpng/zlib/1.2.13/zlib-1.2.13.tar.xz which fails then https://www.zlib.net//zlib-1.2.13.tar.xz where it finds and builds 1.2.13.  Build then continues BUT 1.2.12 does not work.

The build is now failing in "installing gmp for host"  "mp_limb_t is 32 bits, but the assembler code in this configuration expects 64 bits."

I am trying to cross compile for linux 32 bit arm from a 64 bit linux.  So I am pretty much lost as to what NG wants.  Help appreciated
  
  

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/11240930/build.log)
[config_beforeedits.txt](https://github.com/crosstool-ng/crosstool-ng/files/11240943/config_beforeedits.txt)

**Comment by Charlie25466** [comment] 2023-04-16 00:00
well I intended to set versions to 1.2.11 but have verified I set them to 1.2.13 -- no idea why or how it worked but build got a lot further.  log file confirms 1.2.13 is set.  Build log shows it trying to download from http://downloads.sourceforge.net/project/libpng/zlib/1.2.13/zlib-1.2.13.tar.xz which fails then https://www.zlib.net//zlib-1.2.13.tar.xz where it finds and builds 1.2.13.  build then continues BUT 1.2.12 does not work.

**Comment by cpackham** [comment] 2023-04-19 03:24
Your initial problem is a duplicate of #1832. Simplest fix is to manually download zlib.1.2.12 from the location linked in the comments. The zlib mirrors have been updated in master so that's an option if you want to try something newer.

Not sure about the issue with gmp it might be due to partially completed builds from the initial failure and/or your attempts to fix it.

**Closed** 2023-07-23 02:08 UTC
