### ISSUE TITLE
Build failed in step 'Installing gettext for host'

### ISSUE THREAD

**Issue by xmaze** [crosstool-ng/crosstool-ng#1002] opened 2018-07-12 02:36 UTC
- ct-ng version 1.23.0.1
- use in MacOSX 10.13.5  

[INFO ]  =================================================================
[INFO ]  Installing gettext for host
[EXTRA]    Configuring gettext
[EXTRA]    Building gettext
[ERROR]    make[5]: *** [Makefile:2561: /Volumes/arm/cross-compiles/build/.build/src/gettext-0.19.8.1/gettext-tools/src/Makefile.in] Error 127
[ERROR]    make[4]: *** [Makefile:2026: all-recursive] Error 1
[ERROR]    make[3]: *** [Makefile:1892: all] Error 2
[ERROR]    make[2]: *** [Makefile:414: all-recursive] Error 1
[ERROR]    make[1]: *** [Makefile:370: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing gettext for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@297]
[ERROR]  >>        called from: do_gettext_backend[scripts/build/companion_libs/330-gettext.sh@136]
[ERROR]  >>        called from: do_gettext_for_host[scripts/build/companion_libs/330-gettext.sh@53]
[ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/Cellar/crosstool-ng/1.23.0_1/share/doc/crosstool-ng/crosstool-ng-1.23.0/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 13:04.00)
[13:05] / make: *** [build] Error 1

**Comment by aaron19950321** [comment] 2018-09-08 12:51
I find it.
 Companion tools  --->  [*] automake  select it.
You can find problem in build.log. Say: can not find the automake.

**Comment by roolebo** [comment] 2018-10-29 21:33
@aaron19950321 Thanks, I can confirm that it helps. My target is "x86_64-unknown-linux-gnu".

**Comment by roolebo** [comment] 2018-11-08 21:16
I can't reproduce the issue on master branch. I had it only on ~1.5 years old crosstool-ng from homebrew.

**Comment by stilor** [comment] 2018-11-08 21:52
Probably because `master` now adjusts the timestamps after patching various components so that make for each of them doesn't attempt to re-run the autotools.

**Comment by stilor** [comment] 2018-11-08 21:52
I'll give OP a few days to respond, if he still sees it on master - if not, I'll close the issue.

**Closed** 2018-11-17 21:57 UTC
