### ISSUE TITLE
Build arm toolchain on archlinux machine fails

### ISSUE THREAD

**Issue by dax79** [crosstool-ng/crosstool-ng#437] opened 2016-09-02 09:21 UTC
Hi, i'm not able to build an arm toolchain on archlinux x86_64 pc

```
[INFO ]  Installing final gcc compiler
[ERROR]    cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute
[ERROR]    make[3]: *** [Makefile:1065: cp/except.o] Error 1
[ERROR]    make[2]: *** [Makefile:4118: all-gcc] Error 2
[ERROR]    make[1]: *** [Makefile:874: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@944]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@663]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 47:59.39)
[47:59] / make: *** [/home/davide/toolchains/raspberry/bin/ct-ng:152: build] Error 2
```

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/451626/config.txt)

**Comment by KirillSmirnov** [comment] 2016-09-09 20:24
Please try the latest crosstool-ng snapshot. It seems this issue has already been fixed.

Alternatively you may consider applying this patch:
https://github.com/crosstool-ng/crosstool-ng/commit/5a5fcbe148acf35372ecac145816c3515e6b8839

**Comment by dax79** [comment] 2016-09-13 11:56
Thanks, with the latest snapshot i can build the toolchain.

**Comment by stilor** [comment] 2016-12-05 08:51
Submitter confirmed the issue is fixed in master.

**Closed by stilor** 2016-12-05 08:51 UTC
