### ISSUE TITLE
crosstool-ng fails Installing final gcc compiler on Arch Linux

### ISSUE THREAD

**Issue by itggot-linus-styren** [crosstool-ng/crosstool-ng#482] opened 2016-11-28 11:33 UTC
Running `4.8.10-1-ARCH` I tried installing crosstool-ng. So I downloaded the required packages with the command below:
```bash
$ pacman -Syyu
$ pacman -S flex bison automake gperf libtool patch texinfo ncurses-dev help2man
```
It failed fetching `libiconv-1.14.tar.xz` so I downloaded it manually and placed it in the `.build/tarballs` directory. It failed on `Installing final gcc compiler` with the error:
```
[ALL  ]    In file included from /home/linkan/master_toolchain/ctng/.build/src/gcc-linaro-5.2-2015.11-2/gcc/cp/except.c:1023:0:
[ALL  ]    cfns.gperf: In function 'const char* libc_name_p(const char*, unsigned int)':
[ERROR]    cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute
```
See the attached build.log.zip file.
[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/616096/build.log.zip)

**Comment by KirillSmirnov** [comment] 2016-11-28 21:32
Looks like a duplicate of #437

**Closed** 2016-12-15 19:23 UTC
