### ISSUE TITLE
'Installing native gdb': GMP is missing or unusable

### ISSUE THREAD

**Issue by ryanmwe** [crosstool-ng/crosstool-ng#2084] opened 2024-01-11 07:03 UTC
crosstool-NG version: 1.26.0
Host OS:  Arch Linux x86_64 6.6.10-arch1-1
Config Log:
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/13898471/config.log)
Build Log (had to compress due to file size):
[build.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/13899405/build.tar.gz)

**Comment by abrodkin** [comment] 2024-01-14 12:10
Indeed, gets reproduced with v1.26 release and the following `defconfig`:
```
CT_CONFIG_VERSION="4"
# CT_PREFIX_DIR_RO is not set
CT_ARCH_ARM=y
CT_ARCH_CPU="cortex-a8"
CT_ARCH_FPU="neon"
CT_ARCH_FLOAT_HW=y
CT_TARGET_VENDOR="cortex_a8"
CT_KERNEL_LINUX=y
CT_LINUX_V_5_2=y
CT_BINUTILS_LINKER_LD_GOLD=y
CT_BINUTILS_GOLD_THREADS=y
CT_BINUTILS_LD_WRAPPER=y
CT_BINUTILS_PLUGINS=y
CT_CC_LANG_CXX=y
CT_DEBUG_DUMA=y
CT_DEBUG_GDB=y
# CT_GDB_CROSS_PYTHON is not set
CT_GDB_NATIVE=y
CT_DEBUG_LTRACE=y
CT_DEBUG_STRACE=y
```

**Comment by abrodkin** [comment] 2024-01-14 12:56
Duplicate of https://github.com/crosstool-ng/crosstool-ng/issues/1656.
The problem happens because on the native GDB configuration for some reason host's `libgmp.so` is used, thus test fails, and we get build error.
```
configure:21844: arm-cortex_a8-linux-gnueabihf-gcc -o conftest -mcpu=cortex-a8 -mfpu=neon -mhard-float       -Wl,-EL conftest.c -lncurses -lm  /usr/lib/libgmp.so >&5
~/x-tools/arm-cortex_a8-linux-gnueabihf/bin/../lib/gcc/arm-cortex_a8-linux-gnueabihf/13.2.0/../../../../arm-cortex_a8-linux-gnueabihf/bin/ld.bfd: /usr/lib/libgmp.so: error a
dding symbols: file in wrong format
collect2: error: ld returned 1 exit status

configure:21854: result: no
configure:21878: error: GMP is missing or unusable
```

This change helps:
```diff
diff --git a/scripts/build/debug/300-gdb.sh b/scripts/build/debug/300-gdb.sh
index e23298c7..3b0ba543 100644
--- a/scripts/build/debug/300-gdb.sh
+++ b/scripts/build/debug/300-gdb.sh
@@ -121,6 +121,7 @@ do_debug_gdb_build()
         CT_mkdir_pushd "${CT_BUILD_DIR}/build-gdb-native"

         native_extra_config+=("--program-prefix=")
+        native_extra_config+=("--with-libgmp-prefix=${CT_SYSROOT_DIR}")

         # gdbserver gets enabled by default with gdb
         # since gdbserver was promoted to top-level
```

Will draft a patch soon.

**Comment by ryanmwe** [comment] 2024-01-15 06:14
Still hitting the error even with the change, maybe something wrong with my configuration all together?

**Comment by abrodkin** [comment] 2024-01-15 11:22
> Still hitting the error even with the change, maybe something wrong with my configuration all together?

Could you please share your `.build/arm-cortex_a8-linux-gnueabihf/build/build-gdb-native/gdb/config.log`?
What I'm looking for is in the top of that file there's a command line for `./configure` of GDB. With the change above I have that:
```
 $ ~/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/src/gdb/gdb/configure --srcdir=~/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/src/gdb/gdb --cache-file=./config.cache --prefix=/usr --with-build-sysroot=~/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot --includedir=/usr/include --disable-werror --with-libgmp-prefix=~/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot --disable-gdbserver --with-curses --disable-inprocess-agent --without-zstd --without-uiout --disable-gdbtk --without-x --disable-sim --without-included-gettext --without-develop --sysconfdir=/etc --localstatedir=/var --with-expat --without-libexpat-prefix --with-pkgversion=crosstool-NG 1.26.0.40_6cf65db_dirty --disable-binutils --disable-ld --disable-gas --enable-threads --disable-nls --program-transform-name=s&^&& --disable-option-checking --disable-year2038 --build=x86_64-build_pc-linux-gnu --host=arm-cortex_a8-linux-gnueabihf --target=arm-cortex_a8-linux-gnueabihf
```

And im my case there's `--with-libgmp-prefix=~/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot`. Do you have it as well?

**Comment by ryanmwe** [comment] 2024-01-15 20:28
`  $ /home/cosca/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/src/gdb/gdb/configure --srcdir=/home/cosca/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/src/gdb/gdb --cache-file=./config.cache --prefix=/usr --with-build-sysroot=/home/cosca/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot --includedir=/usr/include --disable-werror --with-libgmp-prefix=/home/cosca/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot --disable-gdbserver --with-curses --disable-inprocess-agent --without-zstd --without-uiout --disable-gdbtk --without-x --disable-sim --without-included-gettext --without-develop --sysconfdir=/etc --localstatedir=/var --with-expat --without-libexpat-prefix --with-pkgversion=crosstool-NG 1.26.0.40_6cf65db_dirty --disable-binutils --disable-ld --disable-gas --enable-threads --disable-nls --program-transform-name=s&^&& --disable-option-checking --disable-year2038 --build=x86_64-build_pc-linux-gnu --host=arm-cortex_a8-linux-gnueabihf --target=arm-cortex_a8-linux-gnueabihf`

[config.log](https://github.com/crosstool-ng/crosstool-ng/files/13942823/config.log)

**Comment by ryanmwe** [comment] 2024-01-15 21:01
Not sure if this matters but I checked `/home/cosca/x-tools/arm-cortex_a8-linux-gnueabihf/arm-cortex_a8-linux-gnueabihf/sysroot` and this is no libgmp.so in there. Not sure if that's just because it failed to build or not though. I've checked and i do have libgmp.so locally
`find / -name libgmp.so 2> /dev/null
/home/cosca/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/openssl-1.0.0/engines/libgmp.so
/home/cosca/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libgmp.so
/home/cosca/.local/share/Steam/ubuntu12_32/steam-runtime.old/usr/lib/i386-linux-gnu/openssl-1.0.0/engines/libgmp.so
/home/cosca/.local/share/Steam/ubuntu12_32/steam-runtime.old/usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libgmp.so
/usr/lib/libgmp.so
/usr/lib32/libgmp.so
/var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/23.08/9873dea07eb2b7a92454f52aa25b11889ee49bed2cf43c0e9a594d348b48bdca/files/lib/x86_64-linux-gnu/libgmp.so
`

**Comment by ryanmwe** [comment] 2024-01-18 20:39
I'm no longer getting this error after installing a different gmp package.

**Comment by abrodkin** [comment] 2024-02-06 18:41
@cpackham care to close this one now?

**Comment by cpackham** [comment] 2024-02-06 18:51
Yep will do. Didn't it used to happen with the Fixes tag? Or am I miss
remembering? Anyway will close manually.

**Closed** 2024-02-06 22:40 UTC
